//
//  PvmntStyleKit.h
//  PvmntApp
//
//  Created by PhilipMeyersIV on 1/12/15.
//  Copyright (c) 2015 Pvmnt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface PvmntStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pvmntTextImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* sidebarMenuBackgroundImageTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pvmntLogoTargets;

// Colors
+ (UIColor*)mainBlack;
+ (UIColor*)pureWhite;
+ (UIColor*)calendarSidebar;
+ (UIColor*)mainSidebarMenu;
+ (UIColor*)gold;
+ (UIColor*)flyerGradientColorStart;
+ (UIColor*)sidewalkCalendarMainCollectionViewBackgroundColor;
+ (UIColor*)filterBarColor;
+ (UIColor*)sidewalkCalendarSideCollectionViewBackgroundColor;

// Gradients
+ (PCGradient*)gradient;

// Drawing Methods
+ (void)drawInsetP;
+ (void)drawDiscoverYourCampus;
+ (void)drawFlyerImageGradientWithDrawRect: (CGRect)drawRect;
+ (void)drawEmptyState;
+ (void)drawCanvas2;
+ (void)drawPvmntLogo;

// Generated Images
+ (UIImage*)imageOfPvmntTextImage;
+ (UIImage*)imageOfSidebarMenuBackgroundImage;
+ (UIImage*)imageOfPvmntLogo;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
