//
//  PvmntStyleKit.m
//  PvmntApp
//
//  Created by PhilipMeyersIV on 1/2/15.
//  Copyright (c) 2015 Pvmnt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PvmntStyleKit.h"


@implementation PvmntStyleKit

#pragma mark Cache

static UIColor* _mainBlack = nil;
static UIColor* _pureWhite = nil;
static UIColor* _calendarSidebar = nil;
static UIColor* _mainSidebarMenu = nil;
static UIColor* _gold = nil;

static UIImage* _imageOfPvmntTextImage = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _mainBlack = [UIColor colorWithRed: 0.094 green: 0.094 blue: 0.094 alpha: 1];
    _pureWhite = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    _calendarSidebar = [UIColor colorWithRed: 0.133 green: 0.133 blue: 0.133 alpha: 1];
    _mainSidebarMenu = [UIColor colorWithRed: 0.118 green: 0.11 blue: 0.11 alpha: 1];
    _gold = [UIColor colorWithRed: 0.655 green: 0.541 blue: 0.357 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)mainBlack { return _mainBlack; }
+ (UIColor*)pureWhite { return _pureWhite; }
+ (UIColor*)calendarSidebar { return _calendarSidebar; }
+ (UIColor*)mainSidebarMenu { return _mainSidebarMenu; }
+ (UIColor*)gold { return _gold; }

#pragma mark Drawing Methods

+ (void)drawInsetP
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* backgroundColor = [UIColor colorWithRed: 0.9 green: 0.9 blue: 0.9 alpha: 0.596];

    //// Shadow Declarations
    UIColor* shadow = UIColor.blackColor;
    CGSize shadowOffset = CGSizeMake(2.1, 2.1);
    CGFloat shadowBlurRadius = 6;

    //// Bezier 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 45.21, 57.25);

    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(11.98, -42.52)];
    [bezier2Path addLineToPoint: CGPointMake(1.14, 8.02)];
    [bezier2Path addCurveToPoint: CGPointMake(27.85, -29.21) controlPoint1: CGPointMake(16.56, 6.81) controlPoint2: CGPointMake(27.85, -13.01)];
    [bezier2Path addCurveToPoint: CGPointMake(8.93, -49.79) controlPoint1: CGPointMake(27.85, -40.41) controlPoint2: CGPointMake(22.36, -49.79)];
    [bezier2Path addCurveToPoint: CGPointMake(-30.6, -13.01) controlPoint1: CGPointMake(-15.8, -49.79) controlPoint2: CGPointMake(-30.6, -36.02)];
    [bezier2Path addCurveToPoint: CGPointMake(-28.46, -2.72) controlPoint1: CGPointMake(-30.6, -5.3) controlPoint2: CGPointMake(-28.62, -4.09)];
    [bezier2Path addCurveToPoint: CGPointMake(-44.79, -17.4) controlPoint1: CGPointMake(-38.99, -2.72) controlPoint2: CGPointMake(-44.79, -6.51)];
    [bezier2Path addCurveToPoint: CGPointMake(8.78, -56.75) controlPoint1: CGPointMake(-44.79, -37.53) controlPoint2: CGPointMake(-16.71, -56.75)];
    [bezier2Path addCurveToPoint: CGPointMake(44.79, -26.94) controlPoint1: CGPointMake(33.81, -56.75) controlPoint2: CGPointMake(44.79, -42.52)];
    [bezier2Path addCurveToPoint: CGPointMake(0.69, 13.62) controlPoint1: CGPointMake(44.79, -7.72) controlPoint2: CGPointMake(28.16, 13.62)];
    [bezier2Path addLineToPoint: CGPointMake(-0.08, 13.62)];
    [bezier2Path addLineToPoint: CGPointMake(-9.39, 56.75)];
    [bezier2Path addLineToPoint: CGPointMake(-31.36, 56.75)];
    [bezier2Path addLineToPoint: CGPointMake(-10.61, -39.5)];
    [bezier2Path addLineToPoint: CGPointMake(11.98, -42.52)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [backgroundColor setFill];
    [bezier2Path fill];

    ////// Bezier 2 Inner Shadow
    CGContextSaveGState(context);
    UIRectClip(bezier2Path.bounds);
    CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

    CGContextSetAlpha(context, CGColorGetAlpha([shadow CGColor]));
    CGContextBeginTransparencyLayer(context, NULL);
    {
        UIColor* opaqueShadow = [shadow colorWithAlphaComponent: 1];
        CGContextSetShadowWithColor(context, shadowOffset, shadowBlurRadius, [opaqueShadow CGColor]);
        CGContextSetBlendMode(context, kCGBlendModeSourceOut);
        CGContextBeginTransparencyLayer(context, NULL);

        [opaqueShadow setFill];
        [bezier2Path fill];

        CGContextEndTransparencyLayer(context);
    }
    CGContextEndTransparencyLayer(context);
    CGContextRestoreGState(context);


    CGContextRestoreGState(context);
}

+ (void)drawPvmntTextImage
{
    //// Color Declarations
    UIColor* color4 = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 1];

    //// Text Drawing
    UIBezierPath* textPath = UIBezierPath.bezierPath;
    [textPath moveToPoint: CGPointMake(21.02, 10.56)];
    [textPath addLineToPoint: CGPointMake(8.55, 69.44)];
    [textPath addLineToPoint: CGPointMake(21.75, 69.44)];
    [textPath addLineToPoint: CGPointMake(27.35, 43.06)];
    [textPath addLineToPoint: CGPointMake(27.8, 43.06)];
    [textPath addCurveToPoint: CGPointMake(54.3, 18.24) controlPoint1: CGPointMake(44.31, 43.06) controlPoint2: CGPointMake(54.3, 30)];
    [textPath addCurveToPoint: CGPointMake(32.66, 0) controlPoint1: CGPointMake(54.3, 8.7) controlPoint2: CGPointMake(47.7, 0)];
    [textPath addCurveToPoint: CGPointMake(0.48, 24.07) controlPoint1: CGPointMake(17.35, 0) controlPoint2: CGPointMake(0.48, 11.76)];
    [textPath addCurveToPoint: CGPointMake(10.29, 33.06) controlPoint1: CGPointMake(0.48, 30.74) controlPoint2: CGPointMake(3.96, 33.06)];
    [textPath addCurveToPoint: CGPointMake(9.01, 26.76) controlPoint1: CGPointMake(10.2, 32.22) controlPoint2: CGPointMake(9.01, 31.48)];
    [textPath addCurveToPoint: CGPointMake(32.76, 4.26) controlPoint1: CGPointMake(9.01, 12.69) controlPoint2: CGPointMake(17.9, 4.26)];
    [textPath addCurveToPoint: CGPointMake(44.13, 16.85) controlPoint1: CGPointMake(40.83, 4.26) controlPoint2: CGPointMake(44.13, 10)];
    [textPath addCurveToPoint: CGPointMake(28.08, 39.63) controlPoint1: CGPointMake(44.13, 26.76) controlPoint2: CGPointMake(37.34, 38.89)];
    [textPath addLineToPoint: CGPointMake(34.59, 8.7)];
    [textPath addLineToPoint: CGPointMake(21.02, 10.56)];
    [textPath closePath];
    [textPath moveToPoint: CGPointMake(83.28, 21.3)];
    [textPath addCurveToPoint: CGPointMake(77.6, 26.3) controlPoint1: CGPointMake(79.43, 21.3) controlPoint2: CGPointMake(77.6, 23.43)];
    [textPath addCurveToPoint: CGPointMake(80.9, 31.02) controlPoint1: CGPointMake(77.6, 28.33) controlPoint2: CGPointMake(78.7, 31.02)];
    [textPath addCurveToPoint: CGPointMake(83.83, 30.09) controlPoint1: CGPointMake(81.63, 31.02) controlPoint2: CGPointMake(83.56, 30.74)];
    [textPath addCurveToPoint: CGPointMake(67.97, 61.02) controlPoint1: CGPointMake(83.83, 40.28) controlPoint2: CGPointMake(76.95, 61.02)];
    [textPath addCurveToPoint: CGPointMake(64.85, 57.96) controlPoint1: CGPointMake(65.77, 61.02) controlPoint2: CGPointMake(64.85, 59.81)];
    [textPath addCurveToPoint: CGPointMake(65.31, 54.63) controlPoint1: CGPointMake(64.85, 57.13) controlPoint2: CGPointMake(65.03, 55.93)];
    [textPath addLineToPoint: CGPointMake(71.91, 23.15)];
    [textPath addLineToPoint: CGPointMake(58.71, 23.15)];
    [textPath addLineToPoint: CGPointMake(52.1, 54.63)];
    [textPath addCurveToPoint: CGPointMake(51.65, 59.07) controlPoint1: CGPointMake(51.74, 56.39) controlPoint2: CGPointMake(51.65, 58.06)];
    [textPath addCurveToPoint: CGPointMake(62.92, 70) controlPoint1: CGPointMake(51.65, 66.39) controlPoint2: CGPointMake(55.96, 70)];
    [textPath addCurveToPoint: CGPointMake(89.06, 29.35) controlPoint1: CGPointMake(81.63, 70) controlPoint2: CGPointMake(89.06, 44.17)];
    [textPath addCurveToPoint: CGPointMake(83.28, 21.3) controlPoint1: CGPointMake(89.06, 25.28) controlPoint2: CGPointMake(87.68, 21.3)];
    [textPath closePath];
    [textPath moveToPoint: CGPointMake(139.49, 35.93)];
    [textPath addCurveToPoint: CGPointMake(135.36, 59.54) controlPoint1: CGPointMake(139.49, 41.85) controlPoint2: CGPointMake(135.36, 53.24)];
    [textPath addCurveToPoint: CGPointMake(146.18, 70) controlPoint1: CGPointMake(135.36, 64.81) controlPoint2: CGPointMake(138.21, 70)];
    [textPath addCurveToPoint: CGPointMake(163.24, 52.87) controlPoint1: CGPointMake(151.04, 70) controlPoint2: CGPointMake(158.1, 68.06)];
    [textPath addLineToPoint: CGPointMake(159.39, 52.87)];
    [textPath addCurveToPoint: CGPointMake(151.68, 61.02) controlPoint1: CGPointMake(157.37, 57.69) controlPoint2: CGPointMake(155.72, 61.02)];
    [textPath addCurveToPoint: CGPointMake(148.02, 57.13) controlPoint1: CGPointMake(148.93, 61.02) controlPoint2: CGPointMake(148.02, 59.44)];
    [textPath addCurveToPoint: CGPointMake(152.42, 33.24) controlPoint1: CGPointMake(148.02, 51.94) controlPoint2: CGPointMake(152.42, 40.74)];
    [textPath addCurveToPoint: CGPointMake(142.24, 22.78) controlPoint1: CGPointMake(152.42, 25.83) controlPoint2: CGPointMake(148.11, 22.78)];
    [textPath addCurveToPoint: CGPointMake(129.49, 30.65) controlPoint1: CGPointMake(138.85, 22.78) controlPoint2: CGPointMake(133.9, 23.8)];
    [textPath addCurveToPoint: CGPointMake(120.05, 22.69) controlPoint1: CGPointMake(128.49, 24.91) controlPoint2: CGPointMake(124.91, 22.69)];
    [textPath addCurveToPoint: CGPointMake(108.86, 27.96) controlPoint1: CGPointMake(116.84, 22.69) controlPoint2: CGPointMake(112.71, 23.52)];
    [textPath addLineToPoint: CGPointMake(109.87, 23.15)];
    [textPath addLineToPoint: CGPointMake(96.67, 23.15)];
    [textPath addLineToPoint: CGPointMake(86.95, 69.44)];
    [textPath addLineToPoint: CGPointMake(100.15, 69.44)];
    [textPath addLineToPoint: CGPointMake(106.39, 39.72)];
    [textPath addCurveToPoint: CGPointMake(113.81, 31.11) controlPoint1: CGPointMake(107.76, 35.09) controlPoint2: CGPointMake(110.24, 31.11)];
    [textPath addCurveToPoint: CGPointMake(116.57, 35.19) controlPoint1: CGPointMake(115.83, 31.11) controlPoint2: CGPointMake(116.57, 33.15)];
    [textPath addCurveToPoint: CGPointMake(116.29, 37.5) controlPoint1: CGPointMake(116.57, 36.02) controlPoint2: CGPointMake(116.47, 36.76)];
    [textPath addLineToPoint: CGPointMake(109.6, 69.44)];
    [textPath addLineToPoint: CGPointMake(122.8, 69.44)];
    [textPath addLineToPoint: CGPointMake(129.04, 39.72)];
    [textPath addCurveToPoint: CGPointMake(136.19, 31.2) controlPoint1: CGPointMake(130.41, 35.09) controlPoint2: CGPointMake(132.89, 31.2)];
    [textPath addCurveToPoint: CGPointMake(139.49, 35.93) controlPoint1: CGPointMake(138.39, 31.2) controlPoint2: CGPointMake(139.49, 32.87)];
    [textPath closePath];
    [textPath moveToPoint: CGPointMake(185.79, 35.93)];
    [textPath addCurveToPoint: CGPointMake(181.67, 59.54) controlPoint1: CGPointMake(185.79, 41.85) controlPoint2: CGPointMake(181.67, 53.24)];
    [textPath addCurveToPoint: CGPointMake(192.49, 70) controlPoint1: CGPointMake(181.67, 64.81) controlPoint2: CGPointMake(184.51, 70)];
    [textPath addCurveToPoint: CGPointMake(209.54, 52.87) controlPoint1: CGPointMake(197.35, 70) controlPoint2: CGPointMake(204.41, 68.06)];
    [textPath addLineToPoint: CGPointMake(205.69, 52.87)];
    [textPath addCurveToPoint: CGPointMake(197.99, 61.02) controlPoint1: CGPointMake(203.68, 57.69) controlPoint2: CGPointMake(202.02, 61.02)];
    [textPath addCurveToPoint: CGPointMake(194.32, 57.13) controlPoint1: CGPointMake(195.24, 61.02) controlPoint2: CGPointMake(194.32, 59.44)];
    [textPath addCurveToPoint: CGPointMake(198.72, 33.24) controlPoint1: CGPointMake(194.32, 51.94) controlPoint2: CGPointMake(198.72, 40.74)];
    [textPath addCurveToPoint: CGPointMake(188.55, 22.78) controlPoint1: CGPointMake(198.72, 25.83) controlPoint2: CGPointMake(194.41, 22.78)];
    [textPath addCurveToPoint: CGPointMake(177.82, 27.96) controlPoint1: CGPointMake(185.7, 22.78) controlPoint2: CGPointMake(181.67, 23.52)];
    [textPath addLineToPoint: CGPointMake(178.83, 23.15)];
    [textPath addLineToPoint: CGPointMake(165.62, 23.15)];
    [textPath addLineToPoint: CGPointMake(155.9, 69.44)];
    [textPath addLineToPoint: CGPointMake(169.11, 69.44)];
    [textPath addLineToPoint: CGPointMake(175.34, 39.72)];
    [textPath addCurveToPoint: CGPointMake(182.49, 31.2) controlPoint1: CGPointMake(176.72, 35.09) controlPoint2: CGPointMake(179.19, 31.2)];
    [textPath addCurveToPoint: CGPointMake(185.79, 35.93) controlPoint1: CGPointMake(184.69, 31.2) controlPoint2: CGPointMake(185.79, 32.87)];
    [textPath closePath];
    [textPath moveToPoint: CGPointMake(224.76, 26.85)];
    [textPath addLineToPoint: CGPointMake(230.27, 26.85)];
    [textPath addLineToPoint: CGPointMake(231, 23.15)];
    [textPath addLineToPoint: CGPointMake(225.5, 23.15)];
    [textPath addCurveToPoint: CGPointMake(228.62, 8.52) controlPoint1: CGPointMake(227.24, 14.81) controlPoint2: CGPointMake(228.62, 8.52)];
    [textPath addLineToPoint: CGPointMake(215.05, 10.37)];
    [textPath addLineToPoint: CGPointMake(212.29, 23.15)];
    [textPath addLineToPoint: CGPointMake(209.27, 23.15)];
    [textPath addLineToPoint: CGPointMake(208.53, 26.85)];
    [textPath addLineToPoint: CGPointMake(211.56, 26.85)];
    [textPath addLineToPoint: CGPointMake(205.69, 54.63)];
    [textPath addCurveToPoint: CGPointMake(205.14, 59.54) controlPoint1: CGPointMake(205.33, 56.3) controlPoint2: CGPointMake(205.14, 57.96)];
    [textPath addCurveToPoint: CGPointMake(214.31, 70) controlPoint1: CGPointMake(205.14, 65.46) controlPoint2: CGPointMake(207.89, 70)];
    [textPath addCurveToPoint: CGPointMake(224.03, 60.93) controlPoint1: CGPointMake(217.43, 70) controlPoint2: CGPointMake(221.46, 68.89)];
    [textPath addCurveToPoint: CGPointMake(221.65, 61.2) controlPoint1: CGPointMake(223.3, 61.2) controlPoint2: CGPointMake(222.29, 61.2)];
    [textPath addCurveToPoint: CGPointMake(218.44, 57.87) controlPoint1: CGPointMake(219.17, 61.2) controlPoint2: CGPointMake(218.44, 59.81)];
    [textPath addCurveToPoint: CGPointMake(218.9, 54.63) controlPoint1: CGPointMake(218.44, 56.85) controlPoint2: CGPointMake(218.62, 55.74)];
    [textPath addLineToPoint: CGPointMake(224.76, 26.85)];
    [textPath closePath];
    [color4 setFill];
    [textPath fill];


    //// Text 2 Drawing
    UIBezierPath* text2Path = UIBezierPath.bezierPath;
    [text2Path moveToPoint: CGPointMake(6.24, 73.3)];
    [text2Path addLineToPoint: CGPointMake(2.54, 90.31)];
    [text2Path addLineToPoint: CGPointMake(6.46, 90.31)];
    [text2Path addLineToPoint: CGPointMake(6.67, 89.24)];
    [text2Path addCurveToPoint: CGPointMake(9.99, 90.66) controlPoint1: CGPointMake(7.84, 90.23) controlPoint2: CGPointMake(8.96, 90.66)];
    [text2Path addCurveToPoint: CGPointMake(17.52, 77.95) controlPoint1: CGPointMake(14.01, 90.66) controlPoint2: CGPointMake(17.52, 84.11)];
    [text2Path addCurveToPoint: CGPointMake(10.26, 70.25) controlPoint1: CGPointMake(17.52, 73.86) controlPoint2: CGPointMake(15.54, 70.25)];
    [text2Path addCurveToPoint: CGPointMake(0.15, 77.31) controlPoint1: CGPointMake(4.74, 70.25) controlPoint2: CGPointMake(0.15, 73.65)];
    [text2Path addCurveToPoint: CGPointMake(3.06, 79.8) controlPoint1: CGPointMake(0.15, 79.13) controlPoint2: CGPointMake(1.26, 79.8)];
    [text2Path addCurveToPoint: CGPointMake(2.68, 77.98) controlPoint1: CGPointMake(3.03, 79.56) controlPoint2: CGPointMake(2.68, 79.34)];
    [text2Path addCurveToPoint: CGPointMake(9.8, 71.48) controlPoint1: CGPointMake(2.68, 73.91) controlPoint2: CGPointMake(5.75, 71.48)];
    [text2Path addCurveToPoint: CGPointMake(13.77, 76.54) controlPoint1: CGPointMake(12.17, 71.48) controlPoint2: CGPointMake(13.77, 72.9)];
    [text2Path addCurveToPoint: CGPointMake(8.55, 88.31) controlPoint1: CGPointMake(13.77, 81.94) controlPoint2: CGPointMake(11.78, 88.31)];
    [text2Path addCurveToPoint: CGPointMake(7, 87.77) controlPoint1: CGPointMake(8.03, 88.31) controlPoint2: CGPointMake(7.52, 88.15)];
    [text2Path addLineToPoint: CGPointMake(10.26, 72.76)];
    [text2Path addLineToPoint: CGPointMake(6.24, 73.3)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(20.4, 73.38)];
    [text2Path addCurveToPoint: CGPointMake(22.55, 75.49) controlPoint1: CGPointMake(20.4, 74.56) controlPoint2: CGPointMake(21.35, 75.49)];
    [text2Path addCurveToPoint: CGPointMake(24.72, 73.38) controlPoint1: CGPointMake(23.75, 75.49) controlPoint2: CGPointMake(24.72, 74.56)];
    [text2Path addCurveToPoint: CGPointMake(22.55, 71.24) controlPoint1: CGPointMake(24.72, 72.2) controlPoint2: CGPointMake(23.75, 71.24)];
    [text2Path addCurveToPoint: CGPointMake(20.4, 73.38) controlPoint1: CGPointMake(21.35, 71.24) controlPoint2: CGPointMake(20.4, 72.2)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(19.86, 76.94)];
    [text2Path addLineToPoint: CGPointMake(18.01, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(17.79, 87.26) controlPoint1: CGPointMake(17.87, 86.17) controlPoint2: CGPointMake(17.79, 86.75)];
    [text2Path addCurveToPoint: CGPointMake(20.7, 90.47) controlPoint1: CGPointMake(17.79, 89.51) controlPoint2: CGPointMake(19.07, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(26.41, 85.52) controlPoint1: CGPointMake(22.17, 90.47) controlPoint2: CGPointMake(24.86, 89.88)];
    [text2Path addLineToPoint: CGPointMake(25.27, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(22.82, 87.88) controlPoint1: CGPointMake(24.86, 86.86) controlPoint2: CGPointMake(23.88, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(21.71, 86.89) controlPoint1: CGPointMake(22.06, 87.88) controlPoint2: CGPointMake(21.71, 87.64)];
    [text2Path addCurveToPoint: CGPointMake(21.82, 86.03) controlPoint1: CGPointMake(21.71, 86.65) controlPoint2: CGPointMake(21.73, 86.38)];
    [text2Path addLineToPoint: CGPointMake(23.77, 76.94)];
    [text2Path addLineToPoint: CGPointMake(19.86, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(35.65, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(33.7, 86.86) controlPoint1: CGPointMake(35.14, 85.95) controlPoint2: CGPointMake(34.43, 86.43)];
    [text2Path addCurveToPoint: CGPointMake(33.8, 85.85) controlPoint1: CGPointMake(33.78, 86.54) controlPoint2: CGPointMake(33.8, 86.22)];
    [text2Path addCurveToPoint: CGPointMake(33.21, 76.11) controlPoint1: CGPointMake(33.8, 84.08) controlPoint2: CGPointMake(33.53, 83.04)];
    [text2Path addLineToPoint: CGPointMake(29.18, 76.64)];
    [text2Path addCurveToPoint: CGPointMake(25.84, 84.56) controlPoint1: CGPointMake(28.34, 79.26) controlPoint2: CGPointMake(27.36, 81.91)];
    [text2Path addCurveToPoint: CGPointMake(24.4, 87.05) controlPoint1: CGPointMake(25.11, 84.91) controlPoint2: CGPointMake(24.4, 85.82)];
    [text2Path addCurveToPoint: CGPointMake(28.37, 90.47) controlPoint1: CGPointMake(24.4, 88.68) controlPoint2: CGPointMake(25.59, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(32.64, 88.87) controlPoint1: CGPointMake(29.75, 90.47) controlPoint2: CGPointMake(31.49, 90.05)];
    [text2Path addCurveToPoint: CGPointMake(36.79, 85.52) controlPoint1: CGPointMake(33.89, 88.15) controlPoint2: CGPointMake(35.38, 87.13)];
    [text2Path addLineToPoint: CGPointMake(35.65, 85.52)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(27.77, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(27.14, 84.59) controlPoint1: CGPointMake(27.77, 85.07) controlPoint2: CGPointMake(27.5, 84.75)];
    [text2Path addCurveToPoint: CGPointMake(29.35, 79.53) controlPoint1: CGPointMake(28.04, 82.88) controlPoint2: CGPointMake(28.8, 81.27)];
    [text2Path addCurveToPoint: CGPointMake(29.86, 85.87) controlPoint1: CGPointMake(29.62, 83.65) controlPoint2: CGPointMake(29.86, 84.48)];
    [text2Path addCurveToPoint: CGPointMake(27.5, 88.36) controlPoint1: CGPointMake(29.86, 87.74) controlPoint2: CGPointMake(28.69, 88.36)];
    [text2Path addCurveToPoint: CGPointMake(25.84, 86.49) controlPoint1: CGPointMake(26.3, 88.36) controlPoint2: CGPointMake(25.84, 87.74)];
    [text2Path addCurveToPoint: CGPointMake(26.57, 86.84) controlPoint1: CGPointMake(25.98, 86.75) controlPoint2: CGPointMake(26.3, 86.84)];
    [text2Path addCurveToPoint: CGPointMake(27.77, 85.52) controlPoint1: CGPointMake(27.28, 86.84) controlPoint2: CGPointMake(27.77, 86.17)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(43.24, 80.79)];
    [text2Path addCurveToPoint: CGPointMake(44.19, 81.11) controlPoint1: CGPointMake(43.56, 81) controlPoint2: CGPointMake(43.89, 81.11)];
    [text2Path addCurveToPoint: CGPointMake(45.63, 79.16) controlPoint1: CGPointMake(44.98, 81.11) controlPoint2: CGPointMake(45.63, 80.47)];
    [text2Path addCurveToPoint: CGPointMake(42.61, 76.7) controlPoint1: CGPointMake(45.63, 77.93) controlPoint2: CGPointMake(45.03, 76.7)];
    [text2Path addCurveToPoint: CGPointMake(35.3, 86.22) controlPoint1: CGPointMake(37.09, 76.7) controlPoint2: CGPointMake(35.3, 83.12)];
    [text2Path addCurveToPoint: CGPointMake(39.54, 90.47) controlPoint1: CGPointMake(35.3, 89.24) controlPoint2: CGPointMake(36.98, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(47.02, 85.52) controlPoint1: CGPointMake(43.16, 90.47) controlPoint2: CGPointMake(45.47, 87.99)];
    [text2Path addLineToPoint: CGPointMake(46.09, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(41.28, 88.23) controlPoint1: CGPointMake(44.73, 87.05) controlPoint2: CGPointMake(43.43, 88.23)];
    [text2Path addCurveToPoint: CGPointMake(39.32, 85.98) controlPoint1: CGPointMake(39.98, 88.23) controlPoint2: CGPointMake(39.32, 87.8)];
    [text2Path addCurveToPoint: CGPointMake(42.8, 78.11) controlPoint1: CGPointMake(39.32, 83.01) controlPoint2: CGPointMake(41.09, 78.11)];
    [text2Path addCurveToPoint: CGPointMake(43.56, 79.21) controlPoint1: CGPointMake(43.32, 78.11) controlPoint2: CGPointMake(43.56, 78.54)];
    [text2Path addCurveToPoint: CGPointMake(43.24, 80.79) controlPoint1: CGPointMake(43.56, 79.67) controlPoint2: CGPointMake(43.45, 80.2)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(53.16, 76.7)];
    [text2Path addCurveToPoint: CGPointMake(45.71, 86.19) controlPoint1: CGPointMake(47.56, 76.7) controlPoint2: CGPointMake(45.71, 83.12)];
    [text2Path addCurveToPoint: CGPointMake(50.06, 90.42) controlPoint1: CGPointMake(45.71, 89.24) controlPoint2: CGPointMake(47.53, 90.42)];
    [text2Path addCurveToPoint: CGPointMake(56.56, 82.37) controlPoint1: CGPointMake(53.4, 90.42) controlPoint2: CGPointMake(56.12, 87.32)];
    [text2Path addCurveToPoint: CGPointMake(61.37, 80.15) controlPoint1: CGPointMake(58.54, 82.05) controlPoint2: CGPointMake(60.34, 81.24)];
    [text2Path addLineToPoint: CGPointMake(61.12, 79.43)];
    [text2Path addCurveToPoint: CGPointMake(56.94, 81.03) controlPoint1: CGPointMake(59.96, 80.23) controlPoint2: CGPointMake(58.19, 81.03)];
    [text2Path addCurveToPoint: CGPointMake(56.64, 80.98) controlPoint1: CGPointMake(56.86, 81.03) controlPoint2: CGPointMake(56.75, 81.03)];
    [text2Path addCurveToPoint: CGPointMake(53.16, 76.7) controlPoint1: CGPointMake(56.64, 78.17) controlPoint2: CGPointMake(55.5, 76.7)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(51.15, 88.01)];
    [text2Path addCurveToPoint: CGPointMake(49.76, 85.85) controlPoint1: CGPointMake(50.11, 88.01) controlPoint2: CGPointMake(49.76, 87.61)];
    [text2Path addCurveToPoint: CGPointMake(53.38, 78.33) controlPoint1: CGPointMake(49.76, 83.22) controlPoint2: CGPointMake(51.45, 78.33)];
    [text2Path addCurveToPoint: CGPointMake(54.41, 79.88) controlPoint1: CGPointMake(54.08, 78.33) controlPoint2: CGPointMake(54.36, 78.76)];
    [text2Path addCurveToPoint: CGPointMake(53.57, 81.32) controlPoint1: CGPointMake(53.92, 80.09) controlPoint2: CGPointMake(53.57, 80.58)];
    [text2Path addCurveToPoint: CGPointMake(54.3, 82.45) controlPoint1: CGPointMake(53.57, 81.86) controlPoint2: CGPointMake(53.73, 82.31)];
    [text2Path addCurveToPoint: CGPointMake(51.15, 88.01) controlPoint1: CGPointMake(53.87, 85.6) controlPoint2: CGPointMake(52.48, 88.01)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(67.16, 76.4)];
    [text2Path addCurveToPoint: CGPointMake(65.47, 77.85) controlPoint1: CGPointMake(66.02, 76.4) controlPoint2: CGPointMake(65.47, 77.02)];
    [text2Path addCurveToPoint: CGPointMake(66.45, 79.21) controlPoint1: CGPointMake(65.47, 78.44) controlPoint2: CGPointMake(65.8, 79.21)];
    [text2Path addCurveToPoint: CGPointMake(67.32, 78.94) controlPoint1: CGPointMake(66.67, 79.21) controlPoint2: CGPointMake(67.24, 79.13)];
    [text2Path addCurveToPoint: CGPointMake(62.62, 87.88) controlPoint1: CGPointMake(67.32, 81.89) controlPoint2: CGPointMake(65.28, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(61.7, 87) controlPoint1: CGPointMake(61.97, 87.88) controlPoint2: CGPointMake(61.7, 87.53)];
    [text2Path addCurveToPoint: CGPointMake(61.83, 86.03) controlPoint1: CGPointMake(61.7, 86.75) controlPoint2: CGPointMake(61.75, 86.41)];
    [text2Path addLineToPoint: CGPointMake(63.79, 76.94)];
    [text2Path addLineToPoint: CGPointMake(59.87, 76.94)];
    [text2Path addLineToPoint: CGPointMake(57.92, 86.03)];
    [text2Path addCurveToPoint: CGPointMake(57.78, 87.32) controlPoint1: CGPointMake(57.81, 86.54) controlPoint2: CGPointMake(57.78, 87.02)];
    [text2Path addCurveToPoint: CGPointMake(61.12, 90.47) controlPoint1: CGPointMake(57.78, 89.43) controlPoint2: CGPointMake(59.06, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(68.87, 78.73) controlPoint1: CGPointMake(66.67, 90.47) controlPoint2: CGPointMake(68.87, 83.01)];
    [text2Path addCurveToPoint: CGPointMake(67.16, 76.4) controlPoint1: CGPointMake(68.87, 77.55) controlPoint2: CGPointMake(68.46, 76.4)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(72.95, 85.98)];
    [text2Path addCurveToPoint: CGPointMake(73, 84.91) controlPoint1: CGPointMake(72.95, 85.66) controlPoint2: CGPointMake(72.98, 85.28)];
    [text2Path addCurveToPoint: CGPointMake(79.26, 79.26) controlPoint1: CGPointMake(76.27, 84.72) controlPoint2: CGPointMake(79.26, 82.34)];
    [text2Path addCurveToPoint: CGPointMake(76.27, 76.7) controlPoint1: CGPointMake(79.26, 77.93) controlPoint2: CGPointMake(78.69, 76.7)];
    [text2Path addCurveToPoint: CGPointMake(68.93, 86.22) controlPoint1: CGPointMake(70.69, 76.7) controlPoint2: CGPointMake(68.93, 83.14)];
    [text2Path addCurveToPoint: CGPointMake(73.17, 90.47) controlPoint1: CGPointMake(68.93, 89.24) controlPoint2: CGPointMake(70.61, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(80.64, 85.52) controlPoint1: CGPointMake(76.78, 90.47) controlPoint2: CGPointMake(79.09, 87.99)];
    [text2Path addLineToPoint: CGPointMake(79.72, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(74.91, 88.23) controlPoint1: CGPointMake(78.36, 87.05) controlPoint2: CGPointMake(77.05, 88.23)];
    [text2Path addCurveToPoint: CGPointMake(72.95, 85.98) controlPoint1: CGPointMake(73.6, 88.23) controlPoint2: CGPointMake(72.95, 87.8)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(77.16, 79.21)];
    [text2Path addCurveToPoint: CGPointMake(73.22, 83.62) controlPoint1: CGPointMake(77.16, 81.43) controlPoint2: CGPointMake(75.31, 83.49)];
    [text2Path addCurveToPoint: CGPointMake(76.48, 78.11) controlPoint1: CGPointMake(73.77, 80.98) controlPoint2: CGPointMake(75.1, 78.11)];
    [text2Path addCurveToPoint: CGPointMake(77.16, 79.21) controlPoint1: CGPointMake(77, 78.11) controlPoint2: CGPointMake(77.16, 78.54)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(81.57, 76.94)];
    [text2Path addLineToPoint: CGPointMake(78.69, 90.31)];
    [text2Path addLineToPoint: CGPointMake(82.6, 90.31)];
    [text2Path addLineToPoint: CGPointMake(84.78, 80.15)];
    [text2Path addCurveToPoint: CGPointMake(86.76, 79.13) controlPoint1: CGPointMake(85.45, 79.53) controlPoint2: CGPointMake(85.94, 79.13)];
    [text2Path addCurveToPoint: CGPointMake(88.34, 80.9) controlPoint1: CGPointMake(87.58, 79.13) controlPoint2: CGPointMake(86.81, 80.9)];
    [text2Path addCurveToPoint: CGPointMake(90.29, 78.94) controlPoint1: CGPointMake(89.67, 80.9) controlPoint2: CGPointMake(90.29, 79.88)];
    [text2Path addCurveToPoint: CGPointMake(88.42, 76.94) controlPoint1: CGPointMake(90.29, 77.93) controlPoint2: CGPointMake(89.64, 76.94)];
    [text2Path addCurveToPoint: CGPointMake(85.13, 78.6) controlPoint1: CGPointMake(87.11, 76.94) controlPoint2: CGPointMake(86.08, 77.79)];
    [text2Path addLineToPoint: CGPointMake(85.48, 76.94)];
    [text2Path addLineToPoint: CGPointMake(81.57, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(104.4, 76.94)];
    [text2Path addLineToPoint: CGPointMake(102.5, 85.68)];
    [text2Path addCurveToPoint: CGPointMake(100.38, 87.88) controlPoint1: CGPointMake(102.09, 86.94) controlPoint2: CGPointMake(101.38, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(99.56, 86.7) controlPoint1: CGPointMake(99.75, 87.88) controlPoint2: CGPointMake(99.56, 87.32)];
    [text2Path addCurveToPoint: CGPointMake(99.64, 86.03) controlPoint1: CGPointMake(99.56, 86.49) controlPoint2: CGPointMake(99.59, 86.25)];
    [text2Path addLineToPoint: CGPointMake(101.6, 76.94)];
    [text2Path addLineToPoint: CGPointMake(97.69, 76.94)];
    [text2Path addLineToPoint: CGPointMake(95.84, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(95.62, 87.26) controlPoint1: CGPointMake(95.7, 86.17) controlPoint2: CGPointMake(95.62, 86.75)];
    [text2Path addCurveToPoint: CGPointMake(98.53, 90.47) controlPoint1: CGPointMake(95.62, 89.51) controlPoint2: CGPointMake(96.9, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(101.79, 88.97) controlPoint1: CGPointMake(99.45, 90.47) controlPoint2: CGPointMake(100.65, 90.23)];
    [text2Path addLineToPoint: CGPointMake(101.47, 90.42)];
    [text2Path addCurveToPoint: CGPointMake(97.04, 94.41) controlPoint1: CGPointMake(99.43, 91.03) controlPoint2: CGPointMake(97.04, 92.16)];
    [text2Path addCurveToPoint: CGPointMake(100.08, 97) controlPoint1: CGPointMake(97.04, 96.14) controlPoint2: CGPointMake(98.42, 97)];
    [text2Path addCurveToPoint: CGPointMake(104.97, 92.45) controlPoint1: CGPointMake(101.87, 97) controlPoint2: CGPointMake(104.16, 96.28)];
    [text2Path addLineToPoint: CGPointMake(105.38, 90.53)];
    [text2Path addCurveToPoint: CGPointMake(110.19, 85.52) controlPoint1: CGPointMake(107.07, 90.07) controlPoint2: CGPointMake(109.13, 89.06)];
    [text2Path addLineToPoint: CGPointMake(109.05, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(105.63, 89.35) controlPoint1: CGPointMake(108.29, 87.85) controlPoint2: CGPointMake(107.28, 88.76)];
    [text2Path addLineToPoint: CGPointMake(108.32, 76.94)];
    [text2Path addLineToPoint: CGPointMake(104.4, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(98.53, 94.03)];
    [text2Path addCurveToPoint: CGPointMake(101.19, 91.76) controlPoint1: CGPointMake(98.53, 92.96) controlPoint2: CGPointMake(99.81, 92.27)];
    [text2Path addLineToPoint: CGPointMake(101.03, 92.53)];
    [text2Path addCurveToPoint: CGPointMake(99.45, 94.91) controlPoint1: CGPointMake(100.68, 94.11) controlPoint2: CGPointMake(100.03, 94.91)];
    [text2Path addCurveToPoint: CGPointMake(98.53, 94.03) controlPoint1: CGPointMake(98.86, 94.91) controlPoint2: CGPointMake(98.53, 94.41)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(116.12, 76.7)];
    [text2Path addCurveToPoint: CGPointMake(108.67, 86.19) controlPoint1: CGPointMake(110.52, 76.7) controlPoint2: CGPointMake(108.67, 83.12)];
    [text2Path addCurveToPoint: CGPointMake(113.02, 90.42) controlPoint1: CGPointMake(108.67, 89.24) controlPoint2: CGPointMake(110.49, 90.42)];
    [text2Path addCurveToPoint: CGPointMake(119.52, 82.37) controlPoint1: CGPointMake(116.36, 90.42) controlPoint2: CGPointMake(119.08, 87.32)];
    [text2Path addCurveToPoint: CGPointMake(124.33, 80.15) controlPoint1: CGPointMake(121.5, 82.05) controlPoint2: CGPointMake(123.3, 81.24)];
    [text2Path addLineToPoint: CGPointMake(124.08, 79.43)];
    [text2Path addCurveToPoint: CGPointMake(119.9, 81.03) controlPoint1: CGPointMake(122.91, 80.23) controlPoint2: CGPointMake(121.15, 81.03)];
    [text2Path addCurveToPoint: CGPointMake(119.6, 80.98) controlPoint1: CGPointMake(119.82, 81.03) controlPoint2: CGPointMake(119.71, 81.03)];
    [text2Path addCurveToPoint: CGPointMake(116.12, 76.7) controlPoint1: CGPointMake(119.6, 78.17) controlPoint2: CGPointMake(118.46, 76.7)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(114.11, 88.01)];
    [text2Path addCurveToPoint: CGPointMake(112.72, 85.85) controlPoint1: CGPointMake(113.07, 88.01) controlPoint2: CGPointMake(112.72, 87.61)];
    [text2Path addCurveToPoint: CGPointMake(116.34, 78.33) controlPoint1: CGPointMake(112.72, 83.22) controlPoint2: CGPointMake(114.41, 78.33)];
    [text2Path addCurveToPoint: CGPointMake(117.37, 79.88) controlPoint1: CGPointMake(117.04, 78.33) controlPoint2: CGPointMake(117.31, 78.76)];
    [text2Path addCurveToPoint: CGPointMake(116.53, 81.32) controlPoint1: CGPointMake(116.88, 80.09) controlPoint2: CGPointMake(116.53, 80.58)];
    [text2Path addCurveToPoint: CGPointMake(117.26, 82.45) controlPoint1: CGPointMake(116.53, 81.86) controlPoint2: CGPointMake(116.69, 82.31)];
    [text2Path addCurveToPoint: CGPointMake(114.11, 88.01) controlPoint1: CGPointMake(116.83, 85.6) controlPoint2: CGPointMake(115.44, 88.01)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(129.55, 76.94)];
    [text2Path addLineToPoint: CGPointMake(127.7, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(125.52, 87.88) controlPoint1: CGPointMake(127.29, 86.86) controlPoint2: CGPointMake(126.58, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(124.71, 86.78) controlPoint1: CGPointMake(124.93, 87.88) controlPoint2: CGPointMake(124.71, 87.4)];
    [text2Path addCurveToPoint: CGPointMake(124.79, 86.03) controlPoint1: CGPointMake(124.71, 86.54) controlPoint2: CGPointMake(124.74, 86.3)];
    [text2Path addLineToPoint: CGPointMake(126.75, 76.94)];
    [text2Path addLineToPoint: CGPointMake(122.83, 76.94)];
    [text2Path addLineToPoint: CGPointMake(120.98, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(120.77, 87.26) controlPoint1: CGPointMake(120.85, 86.17) controlPoint2: CGPointMake(120.77, 86.75)];
    [text2Path addCurveToPoint: CGPointMake(123.68, 90.47) controlPoint1: CGPointMake(120.77, 89.51) controlPoint2: CGPointMake(122.04, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(127.7, 87.93) controlPoint1: CGPointMake(124.82, 90.47) controlPoint2: CGPointMake(126.34, 90.13)];
    [text2Path addCurveToPoint: CGPointMake(130.39, 90.47) controlPoint1: CGPointMake(127.86, 89.59) controlPoint2: CGPointMake(128.84, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(135.85, 85.52) controlPoint1: CGPointMake(131.86, 90.47) controlPoint2: CGPointMake(134.31, 89.88)];
    [text2Path addLineToPoint: CGPointMake(134.71, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(132.51, 87.88) controlPoint1: CGPointMake(134.31, 86.86) controlPoint2: CGPointMake(133.57, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(131.4, 86.89) controlPoint1: CGPointMake(131.75, 87.88) controlPoint2: CGPointMake(131.4, 87.64)];
    [text2Path addCurveToPoint: CGPointMake(131.51, 86.03) controlPoint1: CGPointMake(131.4, 86.65) controlPoint2: CGPointMake(131.42, 86.38)];
    [text2Path addLineToPoint: CGPointMake(133.46, 76.94)];
    [text2Path addLineToPoint: CGPointMake(129.55, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(136.56, 76.94)];
    [text2Path addLineToPoint: CGPointMake(133.68, 90.31)];
    [text2Path addLineToPoint: CGPointMake(137.59, 90.31)];
    [text2Path addLineToPoint: CGPointMake(139.77, 80.15)];
    [text2Path addCurveToPoint: CGPointMake(141.75, 79.13) controlPoint1: CGPointMake(140.45, 79.53) controlPoint2: CGPointMake(140.94, 79.13)];
    [text2Path addCurveToPoint: CGPointMake(143.33, 80.9) controlPoint1: CGPointMake(142.57, 79.13) controlPoint2: CGPointMake(141.81, 80.9)];
    [text2Path addCurveToPoint: CGPointMake(145.29, 78.94) controlPoint1: CGPointMake(144.66, 80.9) controlPoint2: CGPointMake(145.29, 79.88)];
    [text2Path addCurveToPoint: CGPointMake(143.41, 76.94) controlPoint1: CGPointMake(145.29, 77.93) controlPoint2: CGPointMake(144.64, 76.94)];
    [text2Path addCurveToPoint: CGPointMake(140.12, 78.6) controlPoint1: CGPointMake(142.11, 76.94) controlPoint2: CGPointMake(141.07, 77.79)];
    [text2Path addLineToPoint: CGPointMake(140.48, 76.94)];
    [text2Path addLineToPoint: CGPointMake(136.56, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(158.42, 80.79)];
    [text2Path addCurveToPoint: CGPointMake(159.37, 81.11) controlPoint1: CGPointMake(158.74, 81) controlPoint2: CGPointMake(159.07, 81.11)];
    [text2Path addCurveToPoint: CGPointMake(160.81, 79.16) controlPoint1: CGPointMake(160.16, 81.11) controlPoint2: CGPointMake(160.81, 80.47)];
    [text2Path addCurveToPoint: CGPointMake(157.79, 76.7) controlPoint1: CGPointMake(160.81, 77.93) controlPoint2: CGPointMake(160.21, 76.7)];
    [text2Path addCurveToPoint: CGPointMake(150.48, 86.22) controlPoint1: CGPointMake(152.27, 76.7) controlPoint2: CGPointMake(150.48, 83.12)];
    [text2Path addCurveToPoint: CGPointMake(154.72, 90.47) controlPoint1: CGPointMake(150.48, 89.24) controlPoint2: CGPointMake(152.17, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(162.2, 85.52) controlPoint1: CGPointMake(158.34, 90.47) controlPoint2: CGPointMake(160.65, 87.99)];
    [text2Path addLineToPoint: CGPointMake(161.27, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(156.46, 88.23) controlPoint1: CGPointMake(159.91, 87.05) controlPoint2: CGPointMake(158.61, 88.23)];
    [text2Path addCurveToPoint: CGPointMake(154.5, 85.98) controlPoint1: CGPointMake(155.16, 88.23) controlPoint2: CGPointMake(154.5, 87.8)];
    [text2Path addCurveToPoint: CGPointMake(157.98, 78.11) controlPoint1: CGPointMake(154.5, 83.01) controlPoint2: CGPointMake(156.27, 78.11)];
    [text2Path addCurveToPoint: CGPointMake(158.74, 79.21) controlPoint1: CGPointMake(158.5, 78.11) controlPoint2: CGPointMake(158.74, 78.54)];
    [text2Path addCurveToPoint: CGPointMake(158.42, 80.79) controlPoint1: CGPointMake(158.74, 79.67) controlPoint2: CGPointMake(158.64, 80.2)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(170.41, 76.94)];
    [text2Path addLineToPoint: CGPointMake(170.11, 78.36)];
    [text2Path addLineToPoint: CGPointMake(170.11, 78.17)];
    [text2Path addCurveToPoint: CGPointMake(167.9, 76.8) controlPoint1: CGPointMake(170.11, 77.39) controlPoint2: CGPointMake(169.45, 76.8)];
    [text2Path addCurveToPoint: CGPointMake(160.92, 86.17) controlPoint1: CGPointMake(163.17, 76.8) controlPoint2: CGPointMake(160.92, 82.56)];
    [text2Path addCurveToPoint: CGPointMake(164.53, 90.47) controlPoint1: CGPointMake(160.92, 89.35) controlPoint2: CGPointMake(162.69, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(168.58, 88.01) controlPoint1: CGPointMake(166.46, 90.47) controlPoint2: CGPointMake(167.74, 89.24)];
    [text2Path addCurveToPoint: CGPointMake(171.25, 90.47) controlPoint1: CGPointMake(168.75, 89.62) controlPoint2: CGPointMake(169.73, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(176.71, 85.52) controlPoint1: CGPointMake(172.72, 90.47) controlPoint2: CGPointMake(175.16, 89.88)];
    [text2Path addLineToPoint: CGPointMake(175.57, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(173.37, 88.04) controlPoint1: CGPointMake(175.16, 86.86) controlPoint2: CGPointMake(174.43, 88.04)];
    [text2Path addCurveToPoint: CGPointMake(172.25, 86.89) controlPoint1: CGPointMake(172.61, 88.04) controlPoint2: CGPointMake(172.25, 87.64)];
    [text2Path addCurveToPoint: CGPointMake(172.36, 86.03) controlPoint1: CGPointMake(172.25, 86.65) controlPoint2: CGPointMake(172.28, 86.38)];
    [text2Path addLineToPoint: CGPointMake(174.32, 76.94)];
    [text2Path addLineToPoint: CGPointMake(170.41, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(168.75, 78.46)];
    [text2Path addCurveToPoint: CGPointMake(169.86, 79.48) controlPoint1: CGPointMake(169.62, 78.46) controlPoint2: CGPointMake(169.86, 79.16)];
    [text2Path addLineToPoint: CGPointMake(168.56, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(166.3, 87.88) controlPoint1: CGPointMake(168.23, 87.08) controlPoint2: CGPointMake(167.09, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(164.94, 85.79) controlPoint1: CGPointMake(165.81, 87.88) controlPoint2: CGPointMake(164.94, 87.85)];
    [text2Path addCurveToPoint: CGPointMake(168.75, 78.46) controlPoint1: CGPointMake(164.94, 83.28) controlPoint2: CGPointMake(166.44, 78.46)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(190.11, 80.63)];
    [text2Path addCurveToPoint: CGPointMake(188.89, 87.45) controlPoint1: CGPointMake(190.11, 82.34) controlPoint2: CGPointMake(188.89, 85.63)];
    [text2Path addCurveToPoint: CGPointMake(192.1, 90.47) controlPoint1: CGPointMake(188.89, 88.97) controlPoint2: CGPointMake(189.73, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(197.16, 85.52) controlPoint1: CGPointMake(193.54, 90.47) controlPoint2: CGPointMake(195.63, 89.91)];
    [text2Path addLineToPoint: CGPointMake(196.01, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(193.73, 87.88) controlPoint1: CGPointMake(195.42, 86.92) controlPoint2: CGPointMake(194.93, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(192.64, 86.75) controlPoint1: CGPointMake(192.91, 87.88) controlPoint2: CGPointMake(192.64, 87.42)];
    [text2Path addCurveToPoint: CGPointMake(193.95, 79.85) controlPoint1: CGPointMake(192.64, 85.26) controlPoint2: CGPointMake(193.95, 82.02)];
    [text2Path addCurveToPoint: CGPointMake(190.93, 76.83) controlPoint1: CGPointMake(193.95, 77.71) controlPoint2: CGPointMake(192.67, 76.83)];
    [text2Path addCurveToPoint: CGPointMake(187.15, 79.1) controlPoint1: CGPointMake(189.92, 76.83) controlPoint2: CGPointMake(188.46, 77.12)];
    [text2Path addCurveToPoint: CGPointMake(184.35, 76.8) controlPoint1: CGPointMake(186.85, 77.45) controlPoint2: CGPointMake(185.79, 76.8)];
    [text2Path addCurveToPoint: CGPointMake(181.04, 78.33) controlPoint1: CGPointMake(183.4, 76.8) controlPoint2: CGPointMake(182.18, 77.04)];
    [text2Path addLineToPoint: CGPointMake(181.33, 76.94)];
    [text2Path addLineToPoint: CGPointMake(177.42, 76.94)];
    [text2Path addLineToPoint: CGPointMake(174.54, 90.31)];
    [text2Path addLineToPoint: CGPointMake(178.45, 90.31)];
    [text2Path addLineToPoint: CGPointMake(180.3, 81.73)];
    [text2Path addCurveToPoint: CGPointMake(182.5, 79.24) controlPoint1: CGPointMake(180.71, 80.39) controlPoint2: CGPointMake(181.44, 79.24)];
    [text2Path addCurveToPoint: CGPointMake(183.32, 80.41) controlPoint1: CGPointMake(183.1, 79.24) controlPoint2: CGPointMake(183.32, 79.83)];
    [text2Path addCurveToPoint: CGPointMake(183.24, 81.08) controlPoint1: CGPointMake(183.32, 80.66) controlPoint2: CGPointMake(183.29, 80.87)];
    [text2Path addLineToPoint: CGPointMake(181.25, 90.31)];
    [text2Path addLineToPoint: CGPointMake(185.17, 90.31)];
    [text2Path addLineToPoint: CGPointMake(187.02, 81.73)];
    [text2Path addCurveToPoint: CGPointMake(189.14, 79.26) controlPoint1: CGPointMake(187.42, 80.39) controlPoint2: CGPointMake(188.16, 79.26)];
    [text2Path addCurveToPoint: CGPointMake(190.11, 80.63) controlPoint1: CGPointMake(189.79, 79.26) controlPoint2: CGPointMake(190.11, 79.75)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(198.08, 75.95)];
    [text2Path addLineToPoint: CGPointMake(193.54, 97)];
    [text2Path addLineToPoint: CGPointMake(197.64, 96.04)];
    [text2Path addLineToPoint: CGPointMake(199.06, 89.51)];
    [text2Path addCurveToPoint: CGPointMake(201.37, 90.47) controlPoint1: CGPointMake(199.36, 90.02) controlPoint2: CGPointMake(200.01, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(208.06, 81.03) controlPoint1: CGPointMake(206.64, 90.47) controlPoint2: CGPointMake(208.06, 84.64)];
    [text2Path addCurveToPoint: CGPointMake(204.74, 76.8) controlPoint1: CGPointMake(208.06, 77.85) controlPoint2: CGPointMake(206.59, 76.8)];
    [text2Path addCurveToPoint: CGPointMake(201.56, 77.95) controlPoint1: CGPointMake(203.38, 76.8) controlPoint2: CGPointMake(202.35, 77.29)];
    [text2Path addLineToPoint: CGPointMake(201.99, 75.95)];
    [text2Path addLineToPoint: CGPointMake(198.08, 75.95)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(200.53, 88.15)];
    [text2Path addCurveToPoint: CGPointMake(199.49, 87.53) controlPoint1: CGPointMake(199.9, 88.15) controlPoint2: CGPointMake(199.6, 87.82)];
    [text2Path addLineToPoint: CGPointMake(201.1, 80.04)];
    [text2Path addCurveToPoint: CGPointMake(202.97, 78.73) controlPoint1: CGPointMake(201.61, 79.18) controlPoint2: CGPointMake(202.37, 78.73)];
    [text2Path addCurveToPoint: CGPointMake(204.33, 80.95) controlPoint1: CGPointMake(203.46, 78.73) controlPoint2: CGPointMake(204.33, 78.89)];
    [text2Path addCurveToPoint: CGPointMake(200.53, 88.15) controlPoint1: CGPointMake(204.33, 83.46) controlPoint2: CGPointMake(203.38, 88.15)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(217.3, 76.94)];
    [text2Path addLineToPoint: CGPointMake(215.45, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(213.28, 87.88) controlPoint1: CGPointMake(215.04, 86.86) controlPoint2: CGPointMake(214.34, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(212.46, 86.78) controlPoint1: CGPointMake(212.68, 87.88) controlPoint2: CGPointMake(212.46, 87.4)];
    [text2Path addCurveToPoint: CGPointMake(212.54, 86.03) controlPoint1: CGPointMake(212.46, 86.54) controlPoint2: CGPointMake(212.49, 86.3)];
    [text2Path addLineToPoint: CGPointMake(214.5, 76.94)];
    [text2Path addLineToPoint: CGPointMake(210.58, 76.94)];
    [text2Path addLineToPoint: CGPointMake(208.74, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(208.52, 87.26) controlPoint1: CGPointMake(208.6, 86.17) controlPoint2: CGPointMake(208.52, 86.75)];
    [text2Path addCurveToPoint: CGPointMake(211.43, 90.47) controlPoint1: CGPointMake(208.52, 89.51) controlPoint2: CGPointMake(209.8, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(215.45, 87.93) controlPoint1: CGPointMake(212.57, 90.47) controlPoint2: CGPointMake(214.09, 90.13)];
    [text2Path addCurveToPoint: CGPointMake(218.14, 90.47) controlPoint1: CGPointMake(215.61, 89.59) controlPoint2: CGPointMake(216.59, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(223.61, 85.52) controlPoint1: CGPointMake(219.61, 90.47) controlPoint2: CGPointMake(222.06, 89.88)];
    [text2Path addLineToPoint: CGPointMake(222.46, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(220.26, 87.88) controlPoint1: CGPointMake(222.06, 86.86) controlPoint2: CGPointMake(221.32, 87.88)];
    [text2Path addCurveToPoint: CGPointMake(219.15, 86.89) controlPoint1: CGPointMake(219.5, 87.88) controlPoint2: CGPointMake(219.15, 87.64)];
    [text2Path addCurveToPoint: CGPointMake(219.26, 86.03) controlPoint1: CGPointMake(219.15, 86.65) controlPoint2: CGPointMake(219.17, 86.38)];
    [text2Path addLineToPoint: CGPointMake(221.21, 76.94)];
    [text2Path addLineToPoint: CGPointMake(217.3, 76.94)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(226.38, 76.64)];
    [text2Path addCurveToPoint: CGPointMake(223.03, 84.56) controlPoint1: CGPointMake(225.54, 79.26) controlPoint2: CGPointMake(224.56, 81.91)];
    [text2Path addCurveToPoint: CGPointMake(221.59, 87.05) controlPoint1: CGPointMake(222.3, 84.91) controlPoint2: CGPointMake(221.59, 85.82)];
    [text2Path addCurveToPoint: CGPointMake(225.56, 90.47) controlPoint1: CGPointMake(221.59, 88.68) controlPoint2: CGPointMake(222.79, 90.47)];
    [text2Path addCurveToPoint: CGPointMake(231, 85.85) controlPoint1: CGPointMake(227.79, 90.47) controlPoint2: CGPointMake(231, 89.32)];
    [text2Path addCurveToPoint: CGPointMake(230.4, 76.11) controlPoint1: CGPointMake(231, 84.08) controlPoint2: CGPointMake(230.73, 83.04)];
    [text2Path addLineToPoint: CGPointMake(226.38, 76.64)];
    [text2Path closePath];
    [text2Path moveToPoint: CGPointMake(224.97, 85.52)];
    [text2Path addCurveToPoint: CGPointMake(224.34, 84.59) controlPoint1: CGPointMake(224.97, 85.07) controlPoint2: CGPointMake(224.69, 84.75)];
    [text2Path addCurveToPoint: CGPointMake(226.54, 79.53) controlPoint1: CGPointMake(225.24, 82.88) controlPoint2: CGPointMake(226, 81.27)];
    [text2Path addCurveToPoint: CGPointMake(227.06, 85.87) controlPoint1: CGPointMake(226.81, 83.65) controlPoint2: CGPointMake(227.06, 84.48)];
    [text2Path addCurveToPoint: CGPointMake(224.69, 88.36) controlPoint1: CGPointMake(227.06, 87.74) controlPoint2: CGPointMake(225.89, 88.36)];
    [text2Path addCurveToPoint: CGPointMake(223.03, 86.49) controlPoint1: CGPointMake(223.5, 88.36) controlPoint2: CGPointMake(223.03, 87.74)];
    [text2Path addCurveToPoint: CGPointMake(223.77, 86.84) controlPoint1: CGPointMake(223.17, 86.75) controlPoint2: CGPointMake(223.5, 86.84)];
    [text2Path addCurveToPoint: CGPointMake(224.97, 85.52) controlPoint1: CGPointMake(224.48, 86.84) controlPoint2: CGPointMake(224.97, 86.17)];
    [text2Path closePath];
    [UIColor.blackColor setFill];
    [text2Path fill];
}

+ (void)drawDiscoverYourCampus
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(6.24, 3.3)];
    [bezierPath addLineToPoint: CGPointMake(2.54, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(6.46, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(6.67, 19.24)];
    [bezierPath addCurveToPoint: CGPointMake(9.99, 20.66) controlPoint1: CGPointMake(7.84, 20.23) controlPoint2: CGPointMake(8.96, 20.66)];
    [bezierPath addCurveToPoint: CGPointMake(17.52, 7.95) controlPoint1: CGPointMake(14.01, 20.66) controlPoint2: CGPointMake(17.52, 14.11)];
    [bezierPath addCurveToPoint: CGPointMake(10.26, 0.25) controlPoint1: CGPointMake(17.52, 3.86) controlPoint2: CGPointMake(15.54, 0.25)];
    [bezierPath addCurveToPoint: CGPointMake(0.15, 7.31) controlPoint1: CGPointMake(4.74, 0.25) controlPoint2: CGPointMake(0.15, 3.65)];
    [bezierPath addCurveToPoint: CGPointMake(3.06, 9.8) controlPoint1: CGPointMake(0.15, 9.13) controlPoint2: CGPointMake(1.26, 9.8)];
    [bezierPath addCurveToPoint: CGPointMake(2.68, 7.98) controlPoint1: CGPointMake(3.03, 9.56) controlPoint2: CGPointMake(2.68, 9.34)];
    [bezierPath addCurveToPoint: CGPointMake(9.8, 1.48) controlPoint1: CGPointMake(2.68, 3.91) controlPoint2: CGPointMake(5.75, 1.48)];
    [bezierPath addCurveToPoint: CGPointMake(13.77, 6.54) controlPoint1: CGPointMake(12.17, 1.48) controlPoint2: CGPointMake(13.77, 2.9)];
    [bezierPath addCurveToPoint: CGPointMake(8.55, 18.31) controlPoint1: CGPointMake(13.77, 11.94) controlPoint2: CGPointMake(11.78, 18.31)];
    [bezierPath addCurveToPoint: CGPointMake(7, 17.77) controlPoint1: CGPointMake(8.03, 18.31) controlPoint2: CGPointMake(7.52, 18.15)];
    [bezierPath addLineToPoint: CGPointMake(10.26, 2.76)];
    [bezierPath addLineToPoint: CGPointMake(6.24, 3.3)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(20.4, 3.38)];
    [bezierPath addCurveToPoint: CGPointMake(22.55, 5.49) controlPoint1: CGPointMake(20.4, 4.56) controlPoint2: CGPointMake(21.35, 5.49)];
    [bezierPath addCurveToPoint: CGPointMake(24.72, 3.38) controlPoint1: CGPointMake(23.75, 5.49) controlPoint2: CGPointMake(24.72, 4.56)];
    [bezierPath addCurveToPoint: CGPointMake(22.55, 1.24) controlPoint1: CGPointMake(24.72, 2.2) controlPoint2: CGPointMake(23.75, 1.24)];
    [bezierPath addCurveToPoint: CGPointMake(20.4, 3.38) controlPoint1: CGPointMake(21.35, 1.24) controlPoint2: CGPointMake(20.4, 2.2)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(19.86, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(18.01, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(17.79, 17.26) controlPoint1: CGPointMake(17.87, 16.17) controlPoint2: CGPointMake(17.79, 16.75)];
    [bezierPath addCurveToPoint: CGPointMake(20.7, 20.47) controlPoint1: CGPointMake(17.79, 19.51) controlPoint2: CGPointMake(19.07, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(26.41, 15.52) controlPoint1: CGPointMake(22.17, 20.47) controlPoint2: CGPointMake(24.86, 19.88)];
    [bezierPath addLineToPoint: CGPointMake(25.27, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(22.82, 17.88) controlPoint1: CGPointMake(24.86, 16.86) controlPoint2: CGPointMake(23.88, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(21.71, 16.89) controlPoint1: CGPointMake(22.06, 17.88) controlPoint2: CGPointMake(21.71, 17.64)];
    [bezierPath addCurveToPoint: CGPointMake(21.82, 16.03) controlPoint1: CGPointMake(21.71, 16.65) controlPoint2: CGPointMake(21.73, 16.38)];
    [bezierPath addLineToPoint: CGPointMake(23.77, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(19.86, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(35.65, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(33.7, 16.86) controlPoint1: CGPointMake(35.14, 15.95) controlPoint2: CGPointMake(34.43, 16.43)];
    [bezierPath addCurveToPoint: CGPointMake(33.8, 15.85) controlPoint1: CGPointMake(33.78, 16.54) controlPoint2: CGPointMake(33.8, 16.22)];
    [bezierPath addCurveToPoint: CGPointMake(33.21, 6.11) controlPoint1: CGPointMake(33.8, 14.08) controlPoint2: CGPointMake(33.53, 13.04)];
    [bezierPath addLineToPoint: CGPointMake(29.18, 6.64)];
    [bezierPath addCurveToPoint: CGPointMake(25.84, 14.56) controlPoint1: CGPointMake(28.34, 9.26) controlPoint2: CGPointMake(27.36, 11.91)];
    [bezierPath addCurveToPoint: CGPointMake(24.4, 17.05) controlPoint1: CGPointMake(25.11, 14.91) controlPoint2: CGPointMake(24.4, 15.82)];
    [bezierPath addCurveToPoint: CGPointMake(28.37, 20.47) controlPoint1: CGPointMake(24.4, 18.68) controlPoint2: CGPointMake(25.59, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(32.64, 18.87) controlPoint1: CGPointMake(29.75, 20.47) controlPoint2: CGPointMake(31.49, 20.04)];
    [bezierPath addCurveToPoint: CGPointMake(36.79, 15.52) controlPoint1: CGPointMake(33.89, 18.15) controlPoint2: CGPointMake(35.38, 17.13)];
    [bezierPath addLineToPoint: CGPointMake(35.65, 15.52)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(27.77, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(27.14, 14.59) controlPoint1: CGPointMake(27.77, 15.07) controlPoint2: CGPointMake(27.5, 14.75)];
    [bezierPath addCurveToPoint: CGPointMake(29.35, 9.53) controlPoint1: CGPointMake(28.04, 12.88) controlPoint2: CGPointMake(28.8, 11.27)];
    [bezierPath addCurveToPoint: CGPointMake(29.86, 15.87) controlPoint1: CGPointMake(29.62, 13.65) controlPoint2: CGPointMake(29.86, 14.48)];
    [bezierPath addCurveToPoint: CGPointMake(27.5, 18.36) controlPoint1: CGPointMake(29.86, 17.74) controlPoint2: CGPointMake(28.69, 18.36)];
    [bezierPath addCurveToPoint: CGPointMake(25.84, 16.49) controlPoint1: CGPointMake(26.3, 18.36) controlPoint2: CGPointMake(25.84, 17.74)];
    [bezierPath addCurveToPoint: CGPointMake(26.57, 16.84) controlPoint1: CGPointMake(25.98, 16.75) controlPoint2: CGPointMake(26.3, 16.84)];
    [bezierPath addCurveToPoint: CGPointMake(27.77, 15.52) controlPoint1: CGPointMake(27.28, 16.84) controlPoint2: CGPointMake(27.77, 16.17)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(43.24, 10.79)];
    [bezierPath addCurveToPoint: CGPointMake(44.19, 11.11) controlPoint1: CGPointMake(43.56, 11) controlPoint2: CGPointMake(43.89, 11.11)];
    [bezierPath addCurveToPoint: CGPointMake(45.63, 9.16) controlPoint1: CGPointMake(44.98, 11.11) controlPoint2: CGPointMake(45.63, 10.47)];
    [bezierPath addCurveToPoint: CGPointMake(42.61, 6.7) controlPoint1: CGPointMake(45.63, 7.93) controlPoint2: CGPointMake(45.03, 6.7)];
    [bezierPath addCurveToPoint: CGPointMake(35.3, 16.22) controlPoint1: CGPointMake(37.09, 6.7) controlPoint2: CGPointMake(35.3, 13.12)];
    [bezierPath addCurveToPoint: CGPointMake(39.54, 20.47) controlPoint1: CGPointMake(35.3, 19.24) controlPoint2: CGPointMake(36.98, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(47.02, 15.52) controlPoint1: CGPointMake(43.16, 20.47) controlPoint2: CGPointMake(45.47, 17.99)];
    [bezierPath addLineToPoint: CGPointMake(46.09, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(41.28, 18.23) controlPoint1: CGPointMake(44.73, 17.05) controlPoint2: CGPointMake(43.43, 18.23)];
    [bezierPath addCurveToPoint: CGPointMake(39.32, 15.98) controlPoint1: CGPointMake(39.98, 18.23) controlPoint2: CGPointMake(39.32, 17.8)];
    [bezierPath addCurveToPoint: CGPointMake(42.8, 8.11) controlPoint1: CGPointMake(39.32, 13.01) controlPoint2: CGPointMake(41.09, 8.11)];
    [bezierPath addCurveToPoint: CGPointMake(43.56, 9.21) controlPoint1: CGPointMake(43.32, 8.11) controlPoint2: CGPointMake(43.56, 8.54)];
    [bezierPath addCurveToPoint: CGPointMake(43.24, 10.79) controlPoint1: CGPointMake(43.56, 9.67) controlPoint2: CGPointMake(43.45, 10.2)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(53.16, 6.7)];
    [bezierPath addCurveToPoint: CGPointMake(45.71, 16.19) controlPoint1: CGPointMake(47.56, 6.7) controlPoint2: CGPointMake(45.71, 13.12)];
    [bezierPath addCurveToPoint: CGPointMake(50.06, 20.42) controlPoint1: CGPointMake(45.71, 19.24) controlPoint2: CGPointMake(47.53, 20.42)];
    [bezierPath addCurveToPoint: CGPointMake(56.56, 12.37) controlPoint1: CGPointMake(53.4, 20.42) controlPoint2: CGPointMake(56.12, 17.32)];
    [bezierPath addCurveToPoint: CGPointMake(61.37, 10.15) controlPoint1: CGPointMake(58.54, 12.05) controlPoint2: CGPointMake(60.34, 11.24)];
    [bezierPath addLineToPoint: CGPointMake(61.12, 9.43)];
    [bezierPath addCurveToPoint: CGPointMake(56.94, 11.03) controlPoint1: CGPointMake(59.96, 10.23) controlPoint2: CGPointMake(58.19, 11.03)];
    [bezierPath addCurveToPoint: CGPointMake(56.64, 10.98) controlPoint1: CGPointMake(56.86, 11.03) controlPoint2: CGPointMake(56.75, 11.03)];
    [bezierPath addCurveToPoint: CGPointMake(53.16, 6.7) controlPoint1: CGPointMake(56.64, 8.17) controlPoint2: CGPointMake(55.5, 6.7)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(51.15, 18.01)];
    [bezierPath addCurveToPoint: CGPointMake(49.76, 15.85) controlPoint1: CGPointMake(50.11, 18.01) controlPoint2: CGPointMake(49.76, 17.61)];
    [bezierPath addCurveToPoint: CGPointMake(53.38, 8.33) controlPoint1: CGPointMake(49.76, 13.22) controlPoint2: CGPointMake(51.45, 8.33)];
    [bezierPath addCurveToPoint: CGPointMake(54.41, 9.88) controlPoint1: CGPointMake(54.08, 8.33) controlPoint2: CGPointMake(54.36, 8.76)];
    [bezierPath addCurveToPoint: CGPointMake(53.57, 11.32) controlPoint1: CGPointMake(53.92, 10.09) controlPoint2: CGPointMake(53.57, 10.58)];
    [bezierPath addCurveToPoint: CGPointMake(54.3, 12.45) controlPoint1: CGPointMake(53.57, 11.86) controlPoint2: CGPointMake(53.73, 12.31)];
    [bezierPath addCurveToPoint: CGPointMake(51.15, 18.01) controlPoint1: CGPointMake(53.87, 15.6) controlPoint2: CGPointMake(52.48, 18.01)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(67.16, 6.4)];
    [bezierPath addCurveToPoint: CGPointMake(65.47, 7.85) controlPoint1: CGPointMake(66.02, 6.4) controlPoint2: CGPointMake(65.47, 7.02)];
    [bezierPath addCurveToPoint: CGPointMake(66.45, 9.21) controlPoint1: CGPointMake(65.47, 8.44) controlPoint2: CGPointMake(65.8, 9.21)];
    [bezierPath addCurveToPoint: CGPointMake(67.32, 8.94) controlPoint1: CGPointMake(66.67, 9.21) controlPoint2: CGPointMake(67.24, 9.13)];
    [bezierPath addCurveToPoint: CGPointMake(62.62, 17.88) controlPoint1: CGPointMake(67.32, 11.89) controlPoint2: CGPointMake(65.28, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(61.7, 17) controlPoint1: CGPointMake(61.97, 17.88) controlPoint2: CGPointMake(61.7, 17.53)];
    [bezierPath addCurveToPoint: CGPointMake(61.83, 16.03) controlPoint1: CGPointMake(61.7, 16.75) controlPoint2: CGPointMake(61.75, 16.41)];
    [bezierPath addLineToPoint: CGPointMake(63.79, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(59.87, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(57.92, 16.03)];
    [bezierPath addCurveToPoint: CGPointMake(57.78, 17.32) controlPoint1: CGPointMake(57.81, 16.54) controlPoint2: CGPointMake(57.78, 17.02)];
    [bezierPath addCurveToPoint: CGPointMake(61.12, 20.47) controlPoint1: CGPointMake(57.78, 19.43) controlPoint2: CGPointMake(59.06, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(68.87, 8.73) controlPoint1: CGPointMake(66.67, 20.47) controlPoint2: CGPointMake(68.87, 13.01)];
    [bezierPath addCurveToPoint: CGPointMake(67.16, 6.4) controlPoint1: CGPointMake(68.87, 7.55) controlPoint2: CGPointMake(68.46, 6.4)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(72.95, 15.98)];
    [bezierPath addCurveToPoint: CGPointMake(73, 14.91) controlPoint1: CGPointMake(72.95, 15.66) controlPoint2: CGPointMake(72.98, 15.28)];
    [bezierPath addCurveToPoint: CGPointMake(79.26, 9.26) controlPoint1: CGPointMake(76.27, 14.72) controlPoint2: CGPointMake(79.26, 12.34)];
    [bezierPath addCurveToPoint: CGPointMake(76.27, 6.7) controlPoint1: CGPointMake(79.26, 7.93) controlPoint2: CGPointMake(78.69, 6.7)];
    [bezierPath addCurveToPoint: CGPointMake(68.93, 16.22) controlPoint1: CGPointMake(70.69, 6.7) controlPoint2: CGPointMake(68.93, 13.14)];
    [bezierPath addCurveToPoint: CGPointMake(73.17, 20.47) controlPoint1: CGPointMake(68.93, 19.24) controlPoint2: CGPointMake(70.61, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(80.64, 15.52) controlPoint1: CGPointMake(76.78, 20.47) controlPoint2: CGPointMake(79.09, 17.99)];
    [bezierPath addLineToPoint: CGPointMake(79.72, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(74.91, 18.23) controlPoint1: CGPointMake(78.36, 17.05) controlPoint2: CGPointMake(77.05, 18.23)];
    [bezierPath addCurveToPoint: CGPointMake(72.95, 15.98) controlPoint1: CGPointMake(73.6, 18.23) controlPoint2: CGPointMake(72.95, 17.8)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(77.16, 9.21)];
    [bezierPath addCurveToPoint: CGPointMake(73.22, 13.62) controlPoint1: CGPointMake(77.16, 11.43) controlPoint2: CGPointMake(75.31, 13.49)];
    [bezierPath addCurveToPoint: CGPointMake(76.48, 8.11) controlPoint1: CGPointMake(73.77, 10.98) controlPoint2: CGPointMake(75.1, 8.11)];
    [bezierPath addCurveToPoint: CGPointMake(77.16, 9.21) controlPoint1: CGPointMake(77, 8.11) controlPoint2: CGPointMake(77.16, 8.54)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(81.57, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(78.69, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(82.6, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(84.78, 10.15)];
    [bezierPath addCurveToPoint: CGPointMake(86.76, 9.13) controlPoint1: CGPointMake(85.45, 9.53) controlPoint2: CGPointMake(85.94, 9.13)];
    [bezierPath addCurveToPoint: CGPointMake(88.34, 10.9) controlPoint1: CGPointMake(87.58, 9.13) controlPoint2: CGPointMake(86.81, 10.9)];
    [bezierPath addCurveToPoint: CGPointMake(90.29, 8.94) controlPoint1: CGPointMake(89.67, 10.9) controlPoint2: CGPointMake(90.29, 9.88)];
    [bezierPath addCurveToPoint: CGPointMake(88.42, 6.94) controlPoint1: CGPointMake(90.29, 7.93) controlPoint2: CGPointMake(89.64, 6.94)];
    [bezierPath addCurveToPoint: CGPointMake(85.13, 8.6) controlPoint1: CGPointMake(87.11, 6.94) controlPoint2: CGPointMake(86.08, 7.79)];
    [bezierPath addLineToPoint: CGPointMake(85.48, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(81.57, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(104.4, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(102.5, 15.68)];
    [bezierPath addCurveToPoint: CGPointMake(100.38, 17.88) controlPoint1: CGPointMake(102.09, 16.94) controlPoint2: CGPointMake(101.38, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(99.56, 16.7) controlPoint1: CGPointMake(99.75, 17.88) controlPoint2: CGPointMake(99.56, 17.32)];
    [bezierPath addCurveToPoint: CGPointMake(99.64, 16.03) controlPoint1: CGPointMake(99.56, 16.49) controlPoint2: CGPointMake(99.59, 16.25)];
    [bezierPath addLineToPoint: CGPointMake(101.6, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(97.69, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(95.84, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(95.62, 17.26) controlPoint1: CGPointMake(95.7, 16.17) controlPoint2: CGPointMake(95.62, 16.75)];
    [bezierPath addCurveToPoint: CGPointMake(98.53, 20.47) controlPoint1: CGPointMake(95.62, 19.51) controlPoint2: CGPointMake(96.9, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(101.79, 18.98) controlPoint1: CGPointMake(99.45, 20.47) controlPoint2: CGPointMake(100.65, 20.23)];
    [bezierPath addLineToPoint: CGPointMake(101.47, 20.42)];
    [bezierPath addCurveToPoint: CGPointMake(97.04, 24.41) controlPoint1: CGPointMake(99.43, 21.03) controlPoint2: CGPointMake(97.04, 22.16)];
    [bezierPath addCurveToPoint: CGPointMake(100.08, 27) controlPoint1: CGPointMake(97.04, 26.14) controlPoint2: CGPointMake(98.42, 27)];
    [bezierPath addCurveToPoint: CGPointMake(104.97, 22.45) controlPoint1: CGPointMake(101.87, 27) controlPoint2: CGPointMake(104.16, 26.28)];
    [bezierPath addLineToPoint: CGPointMake(105.38, 20.53)];
    [bezierPath addCurveToPoint: CGPointMake(110.19, 15.52) controlPoint1: CGPointMake(107.07, 20.07) controlPoint2: CGPointMake(109.13, 19.06)];
    [bezierPath addLineToPoint: CGPointMake(109.05, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(105.63, 19.35) controlPoint1: CGPointMake(108.29, 17.85) controlPoint2: CGPointMake(107.28, 18.76)];
    [bezierPath addLineToPoint: CGPointMake(108.32, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(104.4, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(98.53, 24.03)];
    [bezierPath addCurveToPoint: CGPointMake(101.19, 21.76) controlPoint1: CGPointMake(98.53, 22.96) controlPoint2: CGPointMake(99.81, 22.27)];
    [bezierPath addLineToPoint: CGPointMake(101.03, 22.53)];
    [bezierPath addCurveToPoint: CGPointMake(99.45, 24.91) controlPoint1: CGPointMake(100.68, 24.11) controlPoint2: CGPointMake(100.03, 24.91)];
    [bezierPath addCurveToPoint: CGPointMake(98.53, 24.03) controlPoint1: CGPointMake(98.86, 24.91) controlPoint2: CGPointMake(98.53, 24.41)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(116.12, 6.7)];
    [bezierPath addCurveToPoint: CGPointMake(108.67, 16.19) controlPoint1: CGPointMake(110.52, 6.7) controlPoint2: CGPointMake(108.67, 13.12)];
    [bezierPath addCurveToPoint: CGPointMake(113.02, 20.42) controlPoint1: CGPointMake(108.67, 19.24) controlPoint2: CGPointMake(110.49, 20.42)];
    [bezierPath addCurveToPoint: CGPointMake(119.52, 12.37) controlPoint1: CGPointMake(116.36, 20.42) controlPoint2: CGPointMake(119.08, 17.32)];
    [bezierPath addCurveToPoint: CGPointMake(124.33, 10.15) controlPoint1: CGPointMake(121.5, 12.05) controlPoint2: CGPointMake(123.3, 11.24)];
    [bezierPath addLineToPoint: CGPointMake(124.08, 9.43)];
    [bezierPath addCurveToPoint: CGPointMake(119.9, 11.03) controlPoint1: CGPointMake(122.91, 10.23) controlPoint2: CGPointMake(121.15, 11.03)];
    [bezierPath addCurveToPoint: CGPointMake(119.6, 10.98) controlPoint1: CGPointMake(119.82, 11.03) controlPoint2: CGPointMake(119.71, 11.03)];
    [bezierPath addCurveToPoint: CGPointMake(116.12, 6.7) controlPoint1: CGPointMake(119.6, 8.17) controlPoint2: CGPointMake(118.46, 6.7)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(114.11, 18.01)];
    [bezierPath addCurveToPoint: CGPointMake(112.72, 15.85) controlPoint1: CGPointMake(113.07, 18.01) controlPoint2: CGPointMake(112.72, 17.61)];
    [bezierPath addCurveToPoint: CGPointMake(116.34, 8.33) controlPoint1: CGPointMake(112.72, 13.22) controlPoint2: CGPointMake(114.41, 8.33)];
    [bezierPath addCurveToPoint: CGPointMake(117.37, 9.88) controlPoint1: CGPointMake(117.04, 8.33) controlPoint2: CGPointMake(117.31, 8.76)];
    [bezierPath addCurveToPoint: CGPointMake(116.53, 11.32) controlPoint1: CGPointMake(116.88, 10.09) controlPoint2: CGPointMake(116.53, 10.58)];
    [bezierPath addCurveToPoint: CGPointMake(117.26, 12.45) controlPoint1: CGPointMake(116.53, 11.86) controlPoint2: CGPointMake(116.69, 12.31)];
    [bezierPath addCurveToPoint: CGPointMake(114.11, 18.01) controlPoint1: CGPointMake(116.83, 15.6) controlPoint2: CGPointMake(115.44, 18.01)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(129.55, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(127.7, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(125.52, 17.88) controlPoint1: CGPointMake(127.29, 16.86) controlPoint2: CGPointMake(126.58, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(124.71, 16.78) controlPoint1: CGPointMake(124.93, 17.88) controlPoint2: CGPointMake(124.71, 17.4)];
    [bezierPath addCurveToPoint: CGPointMake(124.79, 16.03) controlPoint1: CGPointMake(124.71, 16.54) controlPoint2: CGPointMake(124.74, 16.3)];
    [bezierPath addLineToPoint: CGPointMake(126.75, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(122.83, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(120.98, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(120.77, 17.26) controlPoint1: CGPointMake(120.85, 16.17) controlPoint2: CGPointMake(120.77, 16.75)];
    [bezierPath addCurveToPoint: CGPointMake(123.68, 20.47) controlPoint1: CGPointMake(120.77, 19.51) controlPoint2: CGPointMake(122.04, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(127.7, 17.93) controlPoint1: CGPointMake(124.82, 20.47) controlPoint2: CGPointMake(126.34, 20.13)];
    [bezierPath addCurveToPoint: CGPointMake(130.39, 20.47) controlPoint1: CGPointMake(127.86, 19.59) controlPoint2: CGPointMake(128.84, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(135.85, 15.52) controlPoint1: CGPointMake(131.86, 20.47) controlPoint2: CGPointMake(134.31, 19.88)];
    [bezierPath addLineToPoint: CGPointMake(134.71, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(132.51, 17.88) controlPoint1: CGPointMake(134.31, 16.86) controlPoint2: CGPointMake(133.57, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(131.4, 16.89) controlPoint1: CGPointMake(131.75, 17.88) controlPoint2: CGPointMake(131.4, 17.64)];
    [bezierPath addCurveToPoint: CGPointMake(131.51, 16.03) controlPoint1: CGPointMake(131.4, 16.65) controlPoint2: CGPointMake(131.42, 16.38)];
    [bezierPath addLineToPoint: CGPointMake(133.46, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(129.55, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(136.56, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(133.68, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(137.59, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(139.77, 10.15)];
    [bezierPath addCurveToPoint: CGPointMake(141.75, 9.13) controlPoint1: CGPointMake(140.45, 9.53) controlPoint2: CGPointMake(140.94, 9.13)];
    [bezierPath addCurveToPoint: CGPointMake(143.33, 10.9) controlPoint1: CGPointMake(142.57, 9.13) controlPoint2: CGPointMake(141.81, 10.9)];
    [bezierPath addCurveToPoint: CGPointMake(145.29, 8.94) controlPoint1: CGPointMake(144.66, 10.9) controlPoint2: CGPointMake(145.29, 9.88)];
    [bezierPath addCurveToPoint: CGPointMake(143.41, 6.94) controlPoint1: CGPointMake(145.29, 7.93) controlPoint2: CGPointMake(144.64, 6.94)];
    [bezierPath addCurveToPoint: CGPointMake(140.12, 8.6) controlPoint1: CGPointMake(142.11, 6.94) controlPoint2: CGPointMake(141.07, 7.79)];
    [bezierPath addLineToPoint: CGPointMake(140.48, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(136.56, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(158.42, 10.79)];
    [bezierPath addCurveToPoint: CGPointMake(159.37, 11.11) controlPoint1: CGPointMake(158.74, 11) controlPoint2: CGPointMake(159.07, 11.11)];
    [bezierPath addCurveToPoint: CGPointMake(160.81, 9.16) controlPoint1: CGPointMake(160.16, 11.11) controlPoint2: CGPointMake(160.81, 10.47)];
    [bezierPath addCurveToPoint: CGPointMake(157.79, 6.7) controlPoint1: CGPointMake(160.81, 7.93) controlPoint2: CGPointMake(160.21, 6.7)];
    [bezierPath addCurveToPoint: CGPointMake(150.48, 16.22) controlPoint1: CGPointMake(152.27, 6.7) controlPoint2: CGPointMake(150.48, 13.12)];
    [bezierPath addCurveToPoint: CGPointMake(154.72, 20.47) controlPoint1: CGPointMake(150.48, 19.24) controlPoint2: CGPointMake(152.17, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(162.2, 15.52) controlPoint1: CGPointMake(158.34, 20.47) controlPoint2: CGPointMake(160.65, 17.99)];
    [bezierPath addLineToPoint: CGPointMake(161.27, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(156.46, 18.23) controlPoint1: CGPointMake(159.91, 17.05) controlPoint2: CGPointMake(158.61, 18.23)];
    [bezierPath addCurveToPoint: CGPointMake(154.5, 15.98) controlPoint1: CGPointMake(155.16, 18.23) controlPoint2: CGPointMake(154.5, 17.8)];
    [bezierPath addCurveToPoint: CGPointMake(157.98, 8.11) controlPoint1: CGPointMake(154.5, 13.01) controlPoint2: CGPointMake(156.27, 8.11)];
    [bezierPath addCurveToPoint: CGPointMake(158.74, 9.21) controlPoint1: CGPointMake(158.5, 8.11) controlPoint2: CGPointMake(158.74, 8.54)];
    [bezierPath addCurveToPoint: CGPointMake(158.42, 10.79) controlPoint1: CGPointMake(158.74, 9.67) controlPoint2: CGPointMake(158.64, 10.2)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(170.41, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(170.11, 8.36)];
    [bezierPath addLineToPoint: CGPointMake(170.11, 8.17)];
    [bezierPath addCurveToPoint: CGPointMake(167.9, 6.8) controlPoint1: CGPointMake(170.11, 7.39) controlPoint2: CGPointMake(169.45, 6.8)];
    [bezierPath addCurveToPoint: CGPointMake(160.92, 16.17) controlPoint1: CGPointMake(163.17, 6.8) controlPoint2: CGPointMake(160.92, 12.55)];
    [bezierPath addCurveToPoint: CGPointMake(164.53, 20.47) controlPoint1: CGPointMake(160.92, 19.35) controlPoint2: CGPointMake(162.69, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(168.58, 18.01) controlPoint1: CGPointMake(166.46, 20.47) controlPoint2: CGPointMake(167.74, 19.24)];
    [bezierPath addCurveToPoint: CGPointMake(171.25, 20.47) controlPoint1: CGPointMake(168.75, 19.62) controlPoint2: CGPointMake(169.73, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(176.71, 15.52) controlPoint1: CGPointMake(172.72, 20.47) controlPoint2: CGPointMake(175.16, 19.88)];
    [bezierPath addLineToPoint: CGPointMake(175.57, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(173.37, 18.04) controlPoint1: CGPointMake(175.16, 16.86) controlPoint2: CGPointMake(174.43, 18.04)];
    [bezierPath addCurveToPoint: CGPointMake(172.25, 16.89) controlPoint1: CGPointMake(172.61, 18.04) controlPoint2: CGPointMake(172.25, 17.64)];
    [bezierPath addCurveToPoint: CGPointMake(172.36, 16.03) controlPoint1: CGPointMake(172.25, 16.65) controlPoint2: CGPointMake(172.28, 16.38)];
    [bezierPath addLineToPoint: CGPointMake(174.32, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(170.41, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(168.75, 8.46)];
    [bezierPath addCurveToPoint: CGPointMake(169.86, 9.48) controlPoint1: CGPointMake(169.62, 8.46) controlPoint2: CGPointMake(169.86, 9.16)];
    [bezierPath addLineToPoint: CGPointMake(168.56, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(166.3, 17.88) controlPoint1: CGPointMake(168.23, 17.08) controlPoint2: CGPointMake(167.09, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(164.94, 15.79) controlPoint1: CGPointMake(165.81, 17.88) controlPoint2: CGPointMake(164.94, 17.85)];
    [bezierPath addCurveToPoint: CGPointMake(168.75, 8.46) controlPoint1: CGPointMake(164.94, 13.28) controlPoint2: CGPointMake(166.44, 8.46)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(190.11, 10.63)];
    [bezierPath addCurveToPoint: CGPointMake(188.89, 17.45) controlPoint1: CGPointMake(190.11, 12.34) controlPoint2: CGPointMake(188.89, 15.63)];
    [bezierPath addCurveToPoint: CGPointMake(192.1, 20.47) controlPoint1: CGPointMake(188.89, 18.98) controlPoint2: CGPointMake(189.73, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(197.16, 15.52) controlPoint1: CGPointMake(193.54, 20.47) controlPoint2: CGPointMake(195.63, 19.91)];
    [bezierPath addLineToPoint: CGPointMake(196.01, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(193.73, 17.88) controlPoint1: CGPointMake(195.42, 16.92) controlPoint2: CGPointMake(194.93, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(192.64, 16.75) controlPoint1: CGPointMake(192.91, 17.88) controlPoint2: CGPointMake(192.64, 17.42)];
    [bezierPath addCurveToPoint: CGPointMake(193.95, 9.85) controlPoint1: CGPointMake(192.64, 15.26) controlPoint2: CGPointMake(193.95, 12.02)];
    [bezierPath addCurveToPoint: CGPointMake(190.93, 6.83) controlPoint1: CGPointMake(193.95, 7.71) controlPoint2: CGPointMake(192.67, 6.83)];
    [bezierPath addCurveToPoint: CGPointMake(187.15, 9.1) controlPoint1: CGPointMake(189.92, 6.83) controlPoint2: CGPointMake(188.46, 7.12)];
    [bezierPath addCurveToPoint: CGPointMake(184.35, 6.8) controlPoint1: CGPointMake(186.85, 7.45) controlPoint2: CGPointMake(185.79, 6.8)];
    [bezierPath addCurveToPoint: CGPointMake(181.04, 8.33) controlPoint1: CGPointMake(183.4, 6.8) controlPoint2: CGPointMake(182.18, 7.04)];
    [bezierPath addLineToPoint: CGPointMake(181.33, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(177.42, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(174.54, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(178.45, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(180.3, 11.73)];
    [bezierPath addCurveToPoint: CGPointMake(182.5, 9.24) controlPoint1: CGPointMake(180.71, 10.39) controlPoint2: CGPointMake(181.44, 9.24)];
    [bezierPath addCurveToPoint: CGPointMake(183.32, 10.41) controlPoint1: CGPointMake(183.1, 9.24) controlPoint2: CGPointMake(183.32, 9.83)];
    [bezierPath addCurveToPoint: CGPointMake(183.24, 11.08) controlPoint1: CGPointMake(183.32, 10.66) controlPoint2: CGPointMake(183.29, 10.87)];
    [bezierPath addLineToPoint: CGPointMake(181.25, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(185.17, 20.31)];
    [bezierPath addLineToPoint: CGPointMake(187.02, 11.73)];
    [bezierPath addCurveToPoint: CGPointMake(189.14, 9.26) controlPoint1: CGPointMake(187.42, 10.39) controlPoint2: CGPointMake(188.16, 9.26)];
    [bezierPath addCurveToPoint: CGPointMake(190.11, 10.63) controlPoint1: CGPointMake(189.79, 9.26) controlPoint2: CGPointMake(190.11, 9.75)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(198.08, 5.95)];
    [bezierPath addLineToPoint: CGPointMake(193.54, 27)];
    [bezierPath addLineToPoint: CGPointMake(197.64, 26.04)];
    [bezierPath addLineToPoint: CGPointMake(199.06, 19.51)];
    [bezierPath addCurveToPoint: CGPointMake(201.37, 20.47) controlPoint1: CGPointMake(199.36, 20.02) controlPoint2: CGPointMake(200.01, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(208.06, 11.03) controlPoint1: CGPointMake(206.64, 20.47) controlPoint2: CGPointMake(208.06, 14.64)];
    [bezierPath addCurveToPoint: CGPointMake(204.74, 6.8) controlPoint1: CGPointMake(208.06, 7.85) controlPoint2: CGPointMake(206.59, 6.8)];
    [bezierPath addCurveToPoint: CGPointMake(201.56, 7.95) controlPoint1: CGPointMake(203.38, 6.8) controlPoint2: CGPointMake(202.35, 7.29)];
    [bezierPath addLineToPoint: CGPointMake(201.99, 5.95)];
    [bezierPath addLineToPoint: CGPointMake(198.08, 5.95)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(200.53, 18.15)];
    [bezierPath addCurveToPoint: CGPointMake(199.49, 17.53) controlPoint1: CGPointMake(199.9, 18.15) controlPoint2: CGPointMake(199.6, 17.82)];
    [bezierPath addLineToPoint: CGPointMake(201.1, 10.04)];
    [bezierPath addCurveToPoint: CGPointMake(202.97, 8.73) controlPoint1: CGPointMake(201.61, 9.18) controlPoint2: CGPointMake(202.37, 8.73)];
    [bezierPath addCurveToPoint: CGPointMake(204.33, 10.95) controlPoint1: CGPointMake(203.46, 8.73) controlPoint2: CGPointMake(204.33, 8.89)];
    [bezierPath addCurveToPoint: CGPointMake(200.53, 18.15) controlPoint1: CGPointMake(204.33, 13.46) controlPoint2: CGPointMake(203.38, 18.15)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(217.3, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(215.45, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(213.28, 17.88) controlPoint1: CGPointMake(215.04, 16.86) controlPoint2: CGPointMake(214.34, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(212.46, 16.78) controlPoint1: CGPointMake(212.68, 17.88) controlPoint2: CGPointMake(212.46, 17.4)];
    [bezierPath addCurveToPoint: CGPointMake(212.54, 16.03) controlPoint1: CGPointMake(212.46, 16.54) controlPoint2: CGPointMake(212.49, 16.3)];
    [bezierPath addLineToPoint: CGPointMake(214.5, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(210.58, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(208.74, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(208.52, 17.26) controlPoint1: CGPointMake(208.6, 16.17) controlPoint2: CGPointMake(208.52, 16.75)];
    [bezierPath addCurveToPoint: CGPointMake(211.43, 20.47) controlPoint1: CGPointMake(208.52, 19.51) controlPoint2: CGPointMake(209.8, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(215.45, 17.93) controlPoint1: CGPointMake(212.57, 20.47) controlPoint2: CGPointMake(214.09, 20.13)];
    [bezierPath addCurveToPoint: CGPointMake(218.14, 20.47) controlPoint1: CGPointMake(215.61, 19.59) controlPoint2: CGPointMake(216.59, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(223.61, 15.52) controlPoint1: CGPointMake(219.61, 20.47) controlPoint2: CGPointMake(222.06, 19.88)];
    [bezierPath addLineToPoint: CGPointMake(222.46, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(220.26, 17.88) controlPoint1: CGPointMake(222.06, 16.86) controlPoint2: CGPointMake(221.32, 17.88)];
    [bezierPath addCurveToPoint: CGPointMake(219.15, 16.89) controlPoint1: CGPointMake(219.5, 17.88) controlPoint2: CGPointMake(219.15, 17.64)];
    [bezierPath addCurveToPoint: CGPointMake(219.26, 16.03) controlPoint1: CGPointMake(219.15, 16.65) controlPoint2: CGPointMake(219.17, 16.38)];
    [bezierPath addLineToPoint: CGPointMake(221.21, 6.94)];
    [bezierPath addLineToPoint: CGPointMake(217.3, 6.94)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(226.38, 6.64)];
    [bezierPath addCurveToPoint: CGPointMake(223.03, 14.56) controlPoint1: CGPointMake(225.54, 9.26) controlPoint2: CGPointMake(224.56, 11.91)];
    [bezierPath addCurveToPoint: CGPointMake(221.59, 17.05) controlPoint1: CGPointMake(222.3, 14.91) controlPoint2: CGPointMake(221.59, 15.82)];
    [bezierPath addCurveToPoint: CGPointMake(225.56, 20.47) controlPoint1: CGPointMake(221.59, 18.68) controlPoint2: CGPointMake(222.79, 20.47)];
    [bezierPath addCurveToPoint: CGPointMake(231, 15.85) controlPoint1: CGPointMake(227.79, 20.47) controlPoint2: CGPointMake(231, 19.32)];
    [bezierPath addCurveToPoint: CGPointMake(230.4, 6.11) controlPoint1: CGPointMake(231, 14.08) controlPoint2: CGPointMake(230.73, 13.04)];
    [bezierPath addLineToPoint: CGPointMake(226.38, 6.64)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(224.97, 15.52)];
    [bezierPath addCurveToPoint: CGPointMake(224.34, 14.59) controlPoint1: CGPointMake(224.97, 15.07) controlPoint2: CGPointMake(224.69, 14.75)];
    [bezierPath addCurveToPoint: CGPointMake(226.54, 9.53) controlPoint1: CGPointMake(225.24, 12.88) controlPoint2: CGPointMake(226, 11.27)];
    [bezierPath addCurveToPoint: CGPointMake(227.06, 15.87) controlPoint1: CGPointMake(226.81, 13.65) controlPoint2: CGPointMake(227.06, 14.48)];
    [bezierPath addCurveToPoint: CGPointMake(224.69, 18.36) controlPoint1: CGPointMake(227.06, 17.74) controlPoint2: CGPointMake(225.89, 18.36)];
    [bezierPath addCurveToPoint: CGPointMake(223.03, 16.49) controlPoint1: CGPointMake(223.5, 18.36) controlPoint2: CGPointMake(223.03, 17.74)];
    [bezierPath addCurveToPoint: CGPointMake(223.77, 16.84) controlPoint1: CGPointMake(223.17, 16.75) controlPoint2: CGPointMake(223.5, 16.84)];
    [bezierPath addCurveToPoint: CGPointMake(224.97, 15.52) controlPoint1: CGPointMake(224.48, 16.84) controlPoint2: CGPointMake(224.97, 16.17)];
    [bezierPath closePath];
    [UIColor.blackColor setFill];
    [bezierPath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfPvmntTextImage
{
    if (_imageOfPvmntTextImage)
        return _imageOfPvmntTextImage;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(601, 339), NO, 0.0f);
    [PvmntStyleKit drawPvmntTextImage];

    _imageOfPvmntTextImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfPvmntTextImage;
}

#pragma mark Customization Infrastructure

- (void)setPvmntTextImageTargets: (NSArray*)pvmntTextImageTargets
{
    _pvmntTextImageTargets = pvmntTextImageTargets;

    for (id target in self.pvmntTextImageTargets)
        [target setImage: PvmntStyleKit.imageOfPvmntTextImage];
}


@end
