//
//  PvmntStyleKit.m
//  PvmntApp
//
//  Created by PhilipMeyersIV on 12/30/14.
//  Copyright (c) 2014 Pvmnt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PvmntStyleKit.h"


@implementation PvmntStyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawInsetP
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* backgroundColor = [UIColor colorWithRed: 0.9 green: 0.9 blue: 0.9 alpha: 0.596];

    //// Shadow Declarations
    UIColor* shadow = UIColor.blackColor;
    CGSize shadowOffset = CGSizeMake(2.1, 2.1);
    CGFloat shadowBlurRadius = 6;

    //// Bezier 2 Drawing
    CGContextSaveGState(context);
    CGContextTranslateCTM(context, 45.21, 57.25);

    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(11.98, -42.52)];
    [bezier2Path addLineToPoint: CGPointMake(1.14, 8.02)];
    [bezier2Path addCurveToPoint: CGPointMake(27.85, -29.21) controlPoint1: CGPointMake(16.56, 6.81) controlPoint2: CGPointMake(27.85, -13.01)];
    [bezier2Path addCurveToPoint: CGPointMake(8.93, -49.79) controlPoint1: CGPointMake(27.85, -40.41) controlPoint2: CGPointMake(22.36, -49.79)];
    [bezier2Path addCurveToPoint: CGPointMake(-30.6, -13.01) controlPoint1: CGPointMake(-15.8, -49.79) controlPoint2: CGPointMake(-30.6, -36.02)];
    [bezier2Path addCurveToPoint: CGPointMake(-28.46, -2.72) controlPoint1: CGPointMake(-30.6, -5.3) controlPoint2: CGPointMake(-28.62, -4.09)];
    [bezier2Path addCurveToPoint: CGPointMake(-44.79, -17.4) controlPoint1: CGPointMake(-38.99, -2.72) controlPoint2: CGPointMake(-44.79, -6.51)];
    [bezier2Path addCurveToPoint: CGPointMake(8.78, -56.75) controlPoint1: CGPointMake(-44.79, -37.53) controlPoint2: CGPointMake(-16.71, -56.75)];
    [bezier2Path addCurveToPoint: CGPointMake(44.79, -26.94) controlPoint1: CGPointMake(33.81, -56.75) controlPoint2: CGPointMake(44.79, -42.52)];
    [bezier2Path addCurveToPoint: CGPointMake(0.69, 13.62) controlPoint1: CGPointMake(44.79, -7.72) controlPoint2: CGPointMake(28.16, 13.62)];
    [bezier2Path addLineToPoint: CGPointMake(-0.08, 13.62)];
    [bezier2Path addLineToPoint: CGPointMake(-9.39, 56.75)];
    [bezier2Path addLineToPoint: CGPointMake(-31.36, 56.75)];
    [bezier2Path addLineToPoint: CGPointMake(-10.61, -39.5)];
    [bezier2Path addLineToPoint: CGPointMake(11.98, -42.52)];
    [bezier2Path closePath];
    bezier2Path.miterLimit = 4;

    [backgroundColor setFill];
    [bezier2Path fill];

    ////// Bezier 2 Inner Shadow
    CGContextSaveGState(context);
    UIRectClip(bezier2Path.bounds);
    CGContextSetShadowWithColor(context, CGSizeZero, 0, NULL);

    CGContextSetAlpha(context, CGColorGetAlpha([shadow CGColor]));
    CGContextBeginTransparencyLayer(context, NULL);
    {
        UIColor* opaqueShadow = [shadow colorWithAlphaComponent: 1];
        CGContextSetShadowWithColor(context, shadowOffset, shadowBlurRadius, [opaqueShadow CGColor]);
        CGContextSetBlendMode(context, kCGBlendModeSourceOut);
        CGContextBeginTransparencyLayer(context, NULL);

        [opaqueShadow setFill];
        [bezier2Path fill];

        CGContextEndTransparencyLayer(context);
    }
    CGContextEndTransparencyLayer(context);
    CGContextRestoreGState(context);


    CGContextRestoreGState(context);
}

@end
