//
//  PvmntStyleKit.h
//  PvmntApp
//
//  Created by PhilipMeyersIV on 12/31/14.
//  Copyright (c) 2014 Pvmnt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PvmntStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* pvmntTextImageTargets;

// Drawing Methods
+ (void)drawInsetP;
+ (void)drawDiscoverYourCampus;

// Generated Images
+ (UIImage*)imageOfPvmntTextImage;

@end
