//
//  PvmntStyleKit.h
//  PvmntApp
//
//  Created by PhilipMeyersIV on 12/30/14.
//  Copyright (c) 2014 Pvmnt. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PvmntStyleKit : NSObject

// Drawing Methods
+ (void)drawInsetP;

@end
